package com.example.rules

import org.opennms.netmgt.xml.event.Event;
import org.opennms.netmgt.model.events.EventUtils;

global org.slf4j.Logger LOG;
global org.opennms.netmgt.correlation.drools.DroolsCorrelationEngine engine;

rule "Event received"
    when
        $e : Event( $uei : uei, $nodeid : nodeid, $ipAddr : interface, $svcName : service, $ifname : getParm("ifName"), $snmpifname : getParm("snmpifname") )
    then
        LOG.info( "UEI: " + $uei + "; Node ID: " + $nodeid + "; IP Address: " + $ipAddr + "; Interface Name: " + $snmpifname + "/" + $ifname + "; Service: " + $svcName);
        retract( $e );
end
