opennms_snmp_collection 'default' do
  include_collections [
    { data_collection_group: 'MIB2' },
    { data_collection_group: '3Com' },
    { data_collection_group: 'Acme Packet' },
    { data_collection_group: 'AKCP sensorProbe' },
    { data_collection_group: 'Alvarion' },
    { data_collection_group: 'APC' },
    { data_collection_group: 'Aruba' },
    { data_collection_group: 'Ascend' },
    { data_collection_group: 'Asterisk' },
    { data_collection_group: 'Bluecat' },
    { data_collection_group: 'Bluecoat' },
    { data_collection_group: 'Bridgewave' },
    { data_collection_group: 'Brocade' },
    { data_collection_group: 'Ceragon' },
    { data_collection_group: 'Checkpoint' },
    { data_collection_group: 'Cisco' },
    { data_collection_group: 'Cisco Nexus' },
    { data_collection_group: 'CLAVISTER' },
    { data_collection_group: 'Colubris' },
    { data_collection_group: 'Concord' },
    { data_collection_group: 'Cyclades' },
    { data_collection_group: 'Dell' },
    { data_collection_group: 'Equallogic' },
    { data_collection_group: 'Ericsson' },
    { data_collection_group: 'Extreme Networks' },
    { data_collection_group: 'F5' },
    { data_collection_group: 'Force10' },
    { data_collection_group: 'Fortinet-Fortigate-Application-v5.2' },
    { data_collection_group: 'Fortinet-Fortigate-ExplicitProxy-v5.2' },
    { data_collection_group: 'Fortinet-Fortigate-HA-v5.2' },
    { data_collection_group: 'Fortinet-Fortigate-Security-v5.2' },
    { data_collection_group: 'Fortinet-Fortigate-System-v5.2' },
    { data_collection_group: 'Foundry Networks' },
    { data_collection_group: 'HP' },
    { data_collection_group: 'HWg' },
    { data_collection_group: 'IBM' },
    { data_collection_group: 'IP Unity' },
    { data_collection_group: 'Juniper' },
    { data_collection_group: 'Konica' },
    { data_collection_group: 'Kyocera' },
    { data_collection_group: 'Lexmark' },
    { data_collection_group: 'Liebert' },
    { data_collection_group: 'Makelsan' },
    { data_collection_group: 'MGE' },
    { data_collection_group: 'Microsoft' },
    { data_collection_group: 'Mikrotik' },
    { data_collection_group: 'Net-SNMP' },
    { data_collection_group: 'Netbotz' },
    { data_collection_group: 'NetEnforcer' },
    { data_collection_group: 'Netscaler' },
    { data_collection_group: 'Netscaler vServer' },
    { data_collection_group: 'Network Appliance' },
    { data_collection_group: 'Nortel' },
    { data_collection_group: 'Novell' },
    { data_collection_group: 'OpenNMS Appliances' },
    { data_collection_group: 'PaloAlto' },
    { data_collection_group: 'pfSense' },
    { data_collection_group: 'Powerware' },
    { data_collection_group: 'Printers' },
    { data_collection_group: 'REF_Compaq-Insight-Manager' },
    { data_collection_group: 'REF_MIB2-Interfaces' },
    { data_collection_group: 'REF_MIB2-Powerethernet' },
    { data_collection_group: 'Riverbed' },
    { data_collection_group: 'Routers' },
    { data_collection_group: 'Savin or Ricoh Printers' },
    { data_collection_group: 'ServerTech' },
    { data_collection_group: 'SNMP-Informant' },
    { data_collection_group: 'SofaWare' },
    { data_collection_group: 'Sonicwall' },
    { data_collection_group: 'SUN Microsystems' },
    { data_collection_group: 'Trango' },
    { data_collection_group: 'VMware-Cim' },
    { data_collection_group: 'VMware6' },
    { data_collection_group: 'VMware7' },
    { data_collection_group: 'WMI' },
    { data_collection_group: 'Zertico' },
    { data_collection_group: 'Zeus' },
  ]
end

opennms_snmp_collection 'ejn' do
  rrd_step 180
  rras [
    'RRA:AVERAGE:0.5:1:3360',
    'RRA:AVERAGE:0.5:20:1488',
    'RRA:AVERAGE:0.5:480:366',
    'RRA:MAX:0.5:480:366',
    'RRA:MIN:0.5:480:366',
  ]
  include_collections [
    { data_collection_group: 'ejn' },
  ]
end
