---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 8980, host: 8988}]
  customize: 
    memory: 1024

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7
    attributes:
      opennms:
        conf: 
          start_timeout: 20
        stable: true
        plugin:
          xml: true
          nsclient: true
      postgresql:
        password:
          postgres: md5c23797e9a303da48b792b4339c426700
        enable_pgdg_yum: true
        version: '9.3'
        dir: /var/lib/pgsql/9.3/data
        config:
          data_directory: /var/lib/pgsql/9.3/data
          shared_preload_libraries: pg_stat_statements
          autovacuum: on
          checkpoint_timeout: 15min
          track_activities: on
          track_counts: on
          vacuum_cost_delay: 50
        config_pgtune:
          max_connections: 160
        pg_hba:
          - addr: ''
            db: all
            method: trust
            type: local
            user: all
          - addr: 127.0.0.1/32
            db: all
            method: trust
            type: host
            user: all
          - addr: '::1/128'
            db: all
            method: trust
            type: host
            user: all
        client:
          packages:
            - postgresql93
            - postgresql93-contrib
            - postgresql93-devel
        server:
          packages:
            - postgresql93-server
          service_name: "postgresql-9.3"
        contrib: 
          packages:
            - postgresql93-contrib
          extensions: 
            - pageinspect
            - pg_buffercache
            - pg_freespacemap
            - pgrowlocks
            - pg_stat_statements
            - pgstattuple
suites:
  - name: default_latest
    run_list:
      - recipe[postgresql::client]
      - recipe[postgresql::server]
      - recipe[postgresql::contrib]
      - recipe[postgresql::config_initdb]
      - recipe[postgresql::config_pgtune]
      - recipe[opennms::default]
  - name: default_17
    run_list:
      - recipe[postgresql::client]
      - recipe[postgresql::server]
      - recipe[postgresql::contrib]
      - recipe[postgresql::config_initdb]
      - recipe[postgresql::config_pgtune]
      - recipe[opennms::default]
    attributes:
      opennms:
        version: "17.1.1-1"
  - name: default_16
    run_list:
      - recipe[postgresql::client]
      - recipe[postgresql::server]
      - recipe[postgresql::contrib]
      - recipe[postgresql::config_initdb]
      - recipe[postgresql::config_pgtune]
      - recipe[opennms::default]
    attributes:
      opennms:
        version: "16.0.4-1"
      postgresql:
        password:
          postgres: md5c23797e9a303da48b792b4339c426700
        enable_pgdg_yum: true
        version: '9.3'
        dir: /var/lib/pgsql/9.3/data
        config:
          data_directory: /var/lib/pgsql/9.3/data
          shared_preload_libraries: pg_stat_statements
          autovacuum: on
          checkpoint_timeout: 15min
          track_activities: on
          track_counts: on
          vacuum_cost_delay: 50
        config_pgtune:
          max_connections: 160
        pg_hba:
          - addr: ''
            db: all
            method: trust
            type: local
            user: all
          - addr: 127.0.0.1/32
            db: all
            method: trust
            type: host
            user: all
          - addr: '::1/128'
            db: all
            method: trust
            type: host
            user: all
        client:
          packages:
            - postgresql93
            - postgresql93-contrib
            - postgresql93-devel
        server:
          packages:
            - postgresql93-server
          service_name: "postgresql-9.3"
        contrib: 
          extensions: 
            - pageinspect
            - pg_buffercache
            - pg_freespacemap
            - pgrowlocks
            - pg_stat_statements
            - pgstattuple
  - name: service_detector
    run_list:
      - recipe[postgresql::client]
      - recipe[postgresql::server]
      - recipe[postgresql::contrib]
      - recipe[postgresql::config_initdb]
      - recipe[postgresql::config_pgtune]
      - recipe[opennms::notemplates]
      - recipe[onms_lwrp_test::service_detector]
  - name: upgrade_step1
    run_list:
      - recipe[postgresql::client]
      - recipe[postgresql::server]
      - recipe[postgresql::contrib]
      - recipe[postgresql::config_initdb]
      - recipe[postgresql::config_pgtune]
      - recipe[opennms::notemplates]
      - recipe[onms_lwrp_test::webopts]
      - recipe[onms_lwrp_test::eventconf]
      - recipe[onms_lwrp_test::collection_graph_file]
      - recipe[onms_lwrp_test::collection_graph]
      - recipe[onms_lwrp_test::response_graph]
    attributes:
      opennms:
        version: "16.0.0-1"
  - name: upgrade_step2
    run_list:
      - recipe[postgresql::client]
      - recipe[postgresql::server]
      - recipe[postgresql::contrib]
      - recipe[postgresql::config_initdb]
      - recipe[postgresql::config_pgtune]
      - recipe[opennms::notemplates]
      - recipe[onms_lwrp_test::webopts]
      - recipe[onms_lwrp_test::eventconf]
      - recipe[onms_lwrp_test::collection_graph_file]
      - recipe[onms_lwrp_test::collection_graph]
      - recipe[onms_lwrp_test::response_graph]
    attributes:
      opennms:
        version: "16.0.4-1"
        upgrade: true
  - name: change_notif
    run_list:
      - recipe[postgresql::client]
      - recipe[postgresql::server]
      - recipe[postgresql::contrib]
      - recipe[postgresql::config_initdb]
      - recipe[postgresql::config_pgtune]
      - recipe[opennms::notemplates]
      - recipe[onms_lwrp_test::destination_path]
      - recipe[onms_lwrp_test::notification_command]
      - recipe[onms_lwrp_test::notifd_autoack]
      - recipe[onms_lwrp_test::notification]
  - name: all
    run_list:
      - recipe[postgresql::client]
      - recipe[postgresql::server]
      - recipe[postgresql::contrib]
      - recipe[postgresql::config_initdb]
      - recipe[postgresql::config_pgtune]
      - recipe[opennms::notemplates]
      - recipe[opennms::nsclient]
      - recipe[onms_lwrp_test::webopts]
      - recipe[onms_lwrp_test::resource_type]
      - recipe[onms_lwrp_test::snmp_collection]
      - recipe[onms_lwrp_test::xml_collection]
      - recipe[onms_lwrp_test::wmi_collection]
      - recipe[onms_lwrp_test::jdbc_collection]
      - recipe[onms_lwrp_test::collection_package]
      - recipe[onms_lwrp_test::snmp_collection_service]
      - recipe[onms_lwrp_test::xml_collection_service]
      - recipe[onms_lwrp_test::wmi_collection_service]
      - recipe[onms_lwrp_test::jdbc_collection_service]
      - recipe[onms_lwrp_test::snmp_collection_group]
      - recipe[onms_lwrp_test::jdbc_query]
      - recipe[onms_lwrp_test::wmi_wpm]
      - recipe[onms_lwrp_test::xml_source]
      - recipe[onms_lwrp_test::xml_group]
      - recipe[onms_lwrp_test::eventconf]
      - recipe[onms_lwrp_test::event]
      - recipe[onms_lwrp_test::poller]
      - recipe[onms_lwrp_test::disco_specific]
      - recipe[onms_lwrp_test::disco_range]
      - recipe[onms_lwrp_test::disco_url]
      - recipe[onms_lwrp_test::foreign_source]
      - recipe[onms_lwrp_test::service_detector]
      - recipe[onms_lwrp_test::policy]
      - recipe[onms_lwrp_test::import]
      - recipe[onms_lwrp_test::import_node]
      - recipe[onms_lwrp_test::import_node_interface]
      - recipe[onms_lwrp_test::import_node_interface_service]
      - recipe[onms_lwrp_test::snmp_config_definition]
      - recipe[onms_lwrp_test::update_snmp_config_definition]
      - recipe[onms_lwrp_test::wmi_config_definition]
      - recipe[onms_lwrp_test::update_wmi_config_definition]
      - recipe[onms_lwrp_test::destination_path]
      - recipe[onms_lwrp_test::notification_command]
      - recipe[onms_lwrp_test::notifd_autoack]
      - recipe[onms_lwrp_test::notification]
      - recipe[onms_lwrp_test::user]
      - recipe[onms_lwrp_test::group]
      - recipe[onms_lwrp_test::role]
      - recipe[onms_lwrp_test::statsd]
      - recipe[onms_lwrp_test::collection_graph_file]
      - recipe[onms_lwrp_test::collection_graph]
      - recipe[onms_lwrp_test::response_graph]
      - recipe[onms_lwrp_test::threshold]
      - recipe[onms_lwrp_test::system_def]
      - recipe[onms_lwrp_test::avail_category]
      - recipe[onms_lwrp_test::avail_view_section]
      - recipe[onms_lwrp_test::wallboard]
      - recipe[onms_lwrp_test::dashlet]
      - recipe[onms_lwrp_test::update_dashlet]
      - recipe[onms_lwrp_test::surveillance_view]
      - recipe[onms_lwrp_test::send_event]
  - name: imports
    run_list:
      - recipe[postgresql::client]
      - recipe[postgresql::server]
      - recipe[postgresql::contrib]
      - recipe[postgresql::config_initdb]
      - recipe[postgresql::config_pgtune]
      - recipe[opennms::notemplates]
      - recipe[onms_lwrp_test::foreign_source]
      - recipe[onms_lwrp_test::policy]
      - recipe[onms_lwrp_test::service_detector]
      - recipe[onms_lwrp_test::import]
      - recipe[onms_lwrp_test::import_node]
      - recipe[onms_lwrp_test::import_node_interface]
      - recipe[onms_lwrp_test::import_node_interface_service]
  - name: notemplates
    run_list:
      - recipe[java]
      - recipe[postgresql::client]
      - recipe[postgresql::server]
      - recipe[postgresql::contrib]
      - recipe[postgresql::config_initdb]
      - recipe[postgresql::config_pgtune]
      - recipe[opennms::notemplates]
