---
verifier:
  name: inspec

driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 8980, host: 8980, auto_correct: false}]
    - ["forwarded_port", {guest: 3000, host: 3000, auto_correct: false}]
    - ["forwarded_port", {guest: 9200, host: 9200, auto_correct: false}]
  customize:
    memory: 2048

provisioner:
  name: chef_zero
  product_version: 14.13.11
  require_chef_omnibus: 14.13.11

platforms:
  - name: centos-6.9
    attributes:
      opennms:
        templates: false
        conf:
          start_timeout: 50
        stable: true
        plugin:
          xml: true
          nsclient: true
  - name: centos-7
    attributes:
      opennms:
        templates: false
        conf:
          start_timeout: 50
        stable: true
        plugin:
          xml: true
          nsclient: true
suites:
  - name: webopts_28
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[opennms::postgres]
      - recipe[openjdk_java11::default]
      - recipe[opennms::default]
      - recipe[onms_lwrp_test::webopts]
    attributes:
      opennms:
        version: 28.0.1-1
    excludes: centos-6.9
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/webopts
  - name: wmi_collection_28
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[opennms::postgres]
      - recipe[openjdk_java11::default]
      - recipe[opennms::default]
      - recipe[onms_lwrp_test::wmi_collection]
    attributes:
      opennms:
        version: 28.0.1-1
    excludes: centos-6.9
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/wmi_collection
  - name: wmi_collection_service_28
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[opennms::postgres]
      - recipe[openjdk_java11::default]
      - recipe[opennms::default]
      - recipe[onms_lwrp_test::wmi_collection_service]
    attributes:
      opennms:
        version: 28.0.1-1
    excludes: centos-6.9
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/wmi_collection_service
  - name: wmi_config_definition_28
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[opennms::postgres]
      - recipe[openjdk_java11::default]
      - recipe[opennms::default]
      - recipe[onms_lwrp_test::wmi_config_definition]
    attributes:
      opennms:
        version: 28.0.1-1
    excludes: centos-6.9
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/wmi_config_definition
  - name: wmi_wpm_28
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[opennms::postgres]
      - recipe[openjdk_java11::default]
      - recipe[opennms::default]
      - recipe[onms_lwrp_test::wmi_wpm]
    attributes:
      opennms:
        version: 28.0.1-1
    excludes: centos-6.9
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/wmi_wpm
  - name: wsman_28
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[opennms::postgres]
      - recipe[openjdk_java11::default]
      - recipe[opennms::default]
      - recipe[onms_lwrp_test::wsman]
    attributes:
      opennms:
        version: 28.0.1-1
    excludes: centos-6.9
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/wsman
  - name: wsman_collection_28
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[opennms::postgres]
      - recipe[openjdk_java11::default]
      - recipe[opennms::default]
      - recipe[onms_lwrp_test::wsman_collection]
    attributes:
      opennms:
        version: 28.0.1-1
    excludes: centos-6.9
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/wsman_collection
  - name: wsman_collection_service_28
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[opennms::postgres]
      - recipe[openjdk_java11::default]
      - recipe[opennms::default]
      - recipe[onms_lwrp_test::wsman_collection_service]
    attributes:
      opennms:
        version: 28.0.1-1
    excludes: centos-6.9
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/wsman_collection_service
  - name: wsman_group_28
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[opennms::postgres]
      - recipe[openjdk_java11::default]
      - recipe[opennms::default]
      - recipe[onms_lwrp_test::wsman_group]
    attributes:
      opennms:
        version: 28.0.1-1
    excludes: centos-6.9
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/wsman_group
  - name: wsman_system_definition_28
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[opennms::postgres]
      - recipe[openjdk_java11::default]
      - recipe[opennms::default]
      - recipe[onms_lwrp_test::wsman_system_definition]
    attributes:
      opennms:
        version: 28.0.1-1
    excludes: centos-6.9
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/wsman_system_definition
  - name: xml_collection_28
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[opennms::postgres]
      - recipe[openjdk_java11::default]
      - recipe[opennms::default]
      - recipe[onms_lwrp_test::xml_collection]
    attributes:
      opennms:
        version: 28.0.1-1
    excludes: centos-6.9
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/xml_collection
  - name: xml_collection_service_28
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[opennms::postgres]
      - recipe[openjdk_java11::default]
      - recipe[opennms::default]
      - recipe[onms_lwrp_test::xml_collection_service]
    attributes:
      opennms:
        version: 28.0.1-1
    excludes: centos-6.9
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/xml_collection_service
  - name: xml_collection_service_change_interval_28
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[opennms::postgres]
      - recipe[openjdk_java11::default]
      - recipe[opennms::default]
      - recipe[onms_lwrp_test::xml_collection_service_change_interval]
    attributes:
      opennms:
        version: 28.0.1-1
    excludes: centos-6.9
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/xml_collection_service_change_interval
  - name: xml_collection_service_change_nothing_28
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[opennms::postgres]
      - recipe[openjdk_java11::default]
      - recipe[opennms::default]
      - recipe[onms_lwrp_test::xml_collection_service_change_nothing]
    attributes:
      opennms:
        version: 28.0.1-1
    excludes: centos-6.9
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/xml_collection_service_change_nothing
  - name: xml_collection_service_change_port_28
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[opennms::postgres]
      - recipe[openjdk_java11::default]
      - recipe[opennms::default]
      - recipe[onms_lwrp_test::xml_collection_service_change_port]
    attributes:
      opennms:
        version: 28.0.1-1
    excludes: centos-6.9
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/xml_collection_service_change_port
  - name: xml_collection_service_change_retrycount_28
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[opennms::postgres]
      - recipe[openjdk_java11::default]
      - recipe[opennms::default]
      - recipe[onms_lwrp_test::xml_collection_service_change_retrycount]
    attributes:
      opennms:
        version: 28.0.1-1
    excludes: centos-6.9
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/xml_collection_service_change_retrycount
  - name: xml_collection_service_change_status_28
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[opennms::postgres]
      - recipe[openjdk_java11::default]
      - recipe[opennms::default]
      - recipe[onms_lwrp_test::xml_collection_service_change_status]
    attributes:
      opennms:
        version: 28.0.1-1
    excludes: centos-6.9
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/xml_collection_service_change_status
  - name: xml_collection_service_change_threshold_28
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[opennms::postgres]
      - recipe[openjdk_java11::default]
      - recipe[opennms::default]
      - recipe[onms_lwrp_test::xml_collection_service_change_threshold]
    attributes:
      opennms:
        version: 28.0.1-1
    excludes: centos-6.9
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/xml_collection_service_change_threshold
  - name: xml_collection_service_change_timeout_28
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[opennms::postgres]
      - recipe[openjdk_java11::default]
      - recipe[opennms::default]
      - recipe[onms_lwrp_test::xml_collection_service_change_timeout]
    attributes:
      opennms:
        version: 28.0.1-1
    excludes: centos-6.9
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/xml_collection_service_change_timeout
  - name: xml_collection_service_change_userdefined_28
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[opennms::postgres]
      - recipe[openjdk_java11::default]
      - recipe[opennms::default]
      - recipe[onms_lwrp_test::xml_collection_service_change_userdefined]
    attributes:
      opennms:
        version: 28.0.1-1
    excludes: centos-6.9
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/xml_collection_service_change_userdefined
  - name: xml_collection_service_delete_28
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[opennms::postgres]
      - recipe[openjdk_java11::default]
      - recipe[opennms::default]
      - recipe[onms_lwrp_test::xml_collection_service_delete]
    attributes:
      opennms:
        version: 28.0.1-1
    excludes: centos-6.9
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/xml_collection_service_delete
  - name: xml_group_28
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[opennms::postgres]
      - recipe[openjdk_java11::default]
      - recipe[opennms::default]
      - recipe[onms_lwrp_test::xml_group]
    attributes:
      opennms:
        version: 28.0.1-1
    excludes: centos-6.9
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/xml_group
  - name: xml_group_delete_28
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[opennms::postgres]
      - recipe[openjdk_java11::default]
      - recipe[opennms::default]
      - recipe[onms_lwrp_test::xml_group_delete]
    attributes:
      opennms:
        version: 28.0.1-1
    excludes: centos-6.9
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/xml_group_delete
  - name: xml_source_28
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[opennms::postgres]
      - recipe[openjdk_java11::default]
      - recipe[opennms::default]
      - recipe[onms_lwrp_test::xml_source]
    attributes:
      opennms:
        version: 28.0.1-1
    excludes: centos-6.9
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/xml_source
  - name: xml_source_delete_28
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[opennms::postgres]
      - recipe[openjdk_java11::default]
      - recipe[opennms::default]
      - recipe[onms_lwrp_test::xml_source_delete]
    attributes:
      opennms:
        version: 28.0.1-1
    excludes: centos-6.9
    verifier:
      inspec_tests:
        - path: test/integration/default
        - path: test/integration/xml_source_delete
  - name: default_28
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[opennms::postgres]
      - recipe[openjdk_java11::default]
      - recipe[opennms::default]
      - recipe[onms_lwrp_test::webopts]
    attributes:
      opennms:
        version: 28.0.1-1
        upgrade: true
        postgresql:
          attempt_upgrade: true
    excludes: centos-6.9
    verifier:
      inspec_tests:
        - path: test/integration/default
  - name: templates_28
    run_list:
      - recipe[yum-centos-ct::default]
      - recipe[opennms::postgres]
      - recipe[openjdk_java11::default]
      - recipe[opennms::default]
      - recipe[onms_lwrp_test::webopts]
    attributes:
      opennms:
        version: 28.0.1-1
        templates: true
    excludes: centos-6.9
    verifier:
      inspec_tests:
        - path: test/integration/default