---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 8980, host: 8988}]
  customize: 
    memory: 1024

provisioner:
  name: chef_zero
#  log_level: debug

platforms:
  - name: centos-6.7
    attributes:
      opennms:
        conf: 
          start_timeout: 20
        stable: true
        plugin:
          xml: true
          nsclient: true
suites:
  - name: default_latest
    run_list:
      - recipe[opennms::postgres]
      - recipe[opennms::default]
  - name: default_17
    run_list:
      - recipe[opennms::postgres]
      - recipe[opennms::default]
    attributes:
      opennms:
        version: "17.1.1-1"
  - name: default_16
    run_list:
      - recipe[opennms::postgres]
      - recipe[opennms::default]
    attributes:
      opennms:
        version: "16.0.4-1"
  - name: service_detector
    run_list:
      - recipe[opennms::postgres]
      - recipe[opennms::notemplates]
      - recipe[onms_lwrp_test::service_detector]
  - name: events
    run_list:
      - recipe[opennms::postgres]
      - recipe[opennms::notemplates]
      - recipe[onms_lwrp_test::webopts]
      - recipe[onms_lwrp_test::eventconf]
      - recipe[onms_lwrp_test::event]
  - name: events_16
    run_list:
      - recipe[opennms::postgres]
      - recipe[opennms::notemplates]
      - recipe[onms_lwrp_test::webopts]
      - recipe[onms_lwrp_test::eventconf]
      - recipe[onms_lwrp_test::event]
    attributes:
      opennms:
        version: "16.0.4-1"
  - name: events_17
    run_list:
      - recipe[opennms::postgres]
      - recipe[opennms::notemplates]
      - recipe[onms_lwrp_test::webopts]
      - recipe[onms_lwrp_test::eventconf]
      - recipe[onms_lwrp_test::event]
    attributes:
      opennms:
        version: "17.1.1-1"
  - name: disco
    run_list:
      - recipe[opennms::postgres]
      - recipe[opennms::notemplates]
      - recipe[onms_lwrp_test::webopts]
      - recipe[onms_lwrp_test::disco_specific]
      - recipe[onms_lwrp_test::disco_range]
      - recipe[onms_lwrp_test::disco_url]
  - name: disco_17
    run_list:
      - recipe[opennms::postgres]
      - recipe[opennms::notemplates]
      - recipe[onms_lwrp_test::webopts]
      - recipe[onms_lwrp_test::disco_specific]
      - recipe[onms_lwrp_test::disco_range]
      - recipe[onms_lwrp_test::disco_url]
    attributes:
      opennms:
        version: "17.1.1-1"
  - name: upgrade_step1
    run_list:
      - recipe[opennms::postgres]
      - recipe[opennms::notemplates]
      - recipe[onms_lwrp_test::webopts]
      - recipe[onms_lwrp_test::eventconf]
      - recipe[onms_lwrp_test::collection_graph_file]
      - recipe[onms_lwrp_test::collection_graph]
      - recipe[onms_lwrp_test::response_graph]
    attributes:
      opennms:
        version: "16.0.4-1"
  - name: upgrade_step2
    run_list:
      - recipe[opennms::postgres]
      - recipe[opennms::notemplates]
      - recipe[onms_lwrp_test::webopts]
      - recipe[onms_lwrp_test::eventconf]
      - recipe[onms_lwrp_test::collection_graph_file]
      - recipe[onms_lwrp_test::collection_graph]
      - recipe[onms_lwrp_test::response_graph]
    attributes:
      opennms:
        version: "17.1.1-1"
        upgrade: true
  - name: upgrade_step3
    run_list:
      - recipe[opennms::postgres]
      - recipe[opennms::notemplates]
      - recipe[onms_lwrp_test::webopts]
      - recipe[onms_lwrp_test::eventconf]
      - recipe[onms_lwrp_test::collection_graph_file]
      - recipe[onms_lwrp_test::collection_graph]
      - recipe[onms_lwrp_test::response_graph]
    attributes:
      opennms:
        upgrade: true
  - name: change_notif
    run_list:
      - recipe[opennms::postgres]
      - recipe[opennms::notemplates]
      - recipe[onms_lwrp_test::destination_path]
      - recipe[onms_lwrp_test::notification_command]
      - recipe[onms_lwrp_test::notifd_autoack]
      - recipe[onms_lwrp_test::notification]
  - name: all
    run_list:
      - recipe[opennms::postgres]
      - recipe[opennms::notemplates]
      - recipe[opennms::nsclient]
      - recipe[onms_lwrp_test::all]
    attributes:
      opennms:
        upgrade: true
  - name: all_17
    run_list:
      - recipe[opennms::postgres]
      - recipe[opennms::notemplates]
      - recipe[opennms::nsclient]
      - recipe[onms_lwrp_test::all]
    attributes:
      opennms:
        version: "17.1.1-1"
        upgrade: true
  - name: all_16
    run_list:
      - recipe[opennms::postgres]
      - recipe[opennms::notemplates]
      - recipe[opennms::nsclient]
      - recipe[onms_lwrp_test::all]
    attributes:
      opennms:
        version: "16.0.4-1"
        upgrade: true
  - name: imports
    run_list:
      - recipe[opennms::postgres]
      - recipe[opennms::notemplates]
      - recipe[onms_lwrp_test::foreign_source]
      - recipe[onms_lwrp_test::policy]
      - recipe[onms_lwrp_test::service_detector]
      - recipe[onms_lwrp_test::import]
      - recipe[onms_lwrp_test::import_node]
      - recipe[onms_lwrp_test::import_node_interface]
      - recipe[onms_lwrp_test::import_node_interface_service]
  - name: notemplates
    run_list:
      - recipe[opennms::postgres]
      - recipe[opennms::notemplates]
