---
driver:
  name: openstack
  flavor_ref: m1.small

provisioner:
  name: chef_zero
  chef_omnibus_url: http://www.getchef.com/chef/install.sh

platforms:
  - name: centos-6.5
    driver_config:
      image_ref: /CentOS/
      username: ec2-user
      floating_ip_pool: 'prov_flat_net'
    attributes: {
                 "yum": {
                         "base": { "baseurl": "http://http-proxy.pe.spanlink.com/base", "mirrorlist": null },
                         "extras": { "baseurl": "http://http-proxy.pe.spanlink.com/extras", "mirrorlist": null },
                         "updates": { "baseurl": "http://http-proxy.pe.spanlink.com/updates", "mirrorlist": null },
                         "epel": { "baseurl": "http://http-proxy.pe.spanlink.com/epel", "mirrorlist": null },
                         "opennms-stable-common": { "baseurl": "http://http-proxy.pe.spanlink.com/opennms-stable-common" },
                         "opennms-stable-rhel6": { "baseurl": "http://http-proxy.pe.spanlink.com/opennms-stable-rhel6" }
                        }, 
                  "opennms": {
                              "conf": {"start_timeout": 20},
                              "stable": false
                              },
                  "postgresql": {
                                "password": { 
                                           "postgres": "md5c23797e9a303da48b792b4339c426700" 
                                          }, 
                                "enable_pgdg_yum": false,
                                
                                "config": {
                                         "autovacuum": "on", 
                                         "checkpoint_timeout": "15min", 
                                         "track_activities": "on", 
                                         "track_counts": "on", 
                                         "vacuum_cost_delay": 50
                                        }, 
                                "pg_hba": [
                                         {
                                          "addr": "", 
                                          "db": "all", 
                                          "method": "trust", 
                                          "type": "local", 
                                          "user": "all"
                                         }, 
                                         {
                                          "addr": "127.0.0.1/32", 
                                          "db": "all", 
                                          "method": "trust", 
                                          "type": "host", 
                                          "user": "all"
                                         },
                                         {
                                          "addr": "::1/128", 
                                          "db": "all", 
                                          "method": "trust", 
                                          "type": "host", 
                                          "user": "all"
                                         }
                                        ], 
                                "client": {
                                         "packages": [
                                                    "postgresql",
                                                    "postgresql-contrib",
                                                    "postgresql-devel"
                                                   ]
                                        },
                                "server": { 
                                         "packages": [
                                                    "postgresql-server"
                                                   ],
                                         "service_name": "postgresql"
                                        }
                              }
                }

suites:
  - name: default
    run_list:
      - recipe[yum-centos::default]
      - recipe[yum-epel::default]
      - recipe[postgresql::client]
      - recipe[postgresql::server]
      - recipe[postgresql::contrib]
      - recipe[postgresql::config_initdb]
      - recipe[postgresql::config_pgtune]
      - recipe[opennms::default]
      - recipe[opennms::nsclient]
      - recipe[opennms::xml]
  - name: lwrps
    run_list:
      - recipe[java]
      - recipe[yum-centos::default]
      - recipe[yum-epel::default]
      - recipe[postgresql::client]
      - recipe[postgresql::server]
      - recipe[postgresql::contrib]
      - recipe[postgresql::config_initdb]
      - recipe[postgresql::config_pgtune]
      - recipe[opennms::notemplates]
      - recipe[opennms::nsclient]
      - recipe[opennms::xml]
      - recipe[opennms::example_webopts]
      - recipe[opennms::example_resource_type]
      - recipe[opennms::example_snmp_collection]
      - recipe[opennms::example_xml_collection]
      - recipe[opennms::example_wmi_collection]
      - recipe[opennms::example_jdbc_collection]
      - recipe[opennms::example_collection_package]
      - recipe[opennms::example_snmp_collection_service]
      - recipe[opennms::example_xml_collection_service]
      - recipe[opennms::example_wmi_collection_service]
      - recipe[opennms::example_jdbc_collection_service]
      - recipe[opennms::example_snmp_collection_group]
      - recipe[opennms::example_jdbc_query]
      - recipe[opennms::example_wmi_wpm]
      - recipe[opennms::example_xml_source]
      - recipe[opennms::example_xml_group]
      - recipe[opennms::example_eventconf]
      - recipe[opennms::example_event]
      - recipe[opennms::example_poller]
      - recipe[opennms::example_disco_specific]
      - recipe[opennms::example_disco_range]
      - recipe[opennms::example_disco_url]
      - recipe[opennms::example_foreign_source]
      - recipe[opennms::example_service_detector]
      - recipe[opennms::example_policy]
      - recipe[opennms::example_import]
      - recipe[opennms::example_import_node]
      - recipe[opennms::example_import_node_interface]
      - recipe[opennms::example_import_node_interface_service]
      - recipe[opennms::example_snmp_config_definition]
      - recipe[opennms::example_update_snmp_config_definition]
      - recipe[opennms::example_wmi_config_definition]
      - recipe[opennms::example_update_wmi_config_definition]
      - recipe[opennms::example_destination_path]
      - recipe[opennms::example_notification_command]
      - recipe[opennms::example_notifd_autoack]
      - recipe[opennms::example_notification]
      - recipe[opennms::example_user]
      - recipe[opennms::example_group]
      - recipe[opennms::example_role]
      - recipe[opennms::example_statsd]
      - recipe[opennms::example_collection_graph_file]
      - recipe[opennms::example_collection_graph]
      - recipe[opennms::example_response_graph]
      - recipe[opennms::example_threshold]
      - recipe[opennms::example_system_def]
      - recipe[opennms::example_avail_category]
      - recipe[opennms::example_avail_view_section]
      - recipe[opennms::example_wallboard]
      - recipe[opennms::example_dashlet]
      - recipe[opennms::example_update_dashlet]
      - recipe[opennms::example_surveillance_view]
      - recipe[opennms::example_send_event]
  - name: notemplates
    run_list:
      - recipe[java]
      - recipe[yum-centos::default]
      - recipe[yum-epel::default]
      - recipe[postgresql::client]
      - recipe[postgresql::server]
      - recipe[postgresql::contrib]
      - recipe[postgresql::config_initdb]
      - recipe[postgresql::config_pgtune]
      - recipe[opennms::notemplates]
  - name: avail_views
    run_list:
      - recipe[java]
      - recipe[yum-centos::default]
      - recipe[yum-epel::default]
      - recipe[postgresql::client]
      - recipe[postgresql::server]
      - recipe[postgresql::contrib]
      - recipe[postgresql::config_initdb]
      - recipe[postgresql::config_pgtune]
      - recipe[opennms::notemplates]
      - recipe[opennms::example_avail_category]
      - recipe[opennms::example_avail_view_section]
  - name: wallboard
    run_list:
      - recipe[java]
      - recipe[yum-centos::default]
      - recipe[yum-epel::default]
      - recipe[postgresql::client]
      - recipe[postgresql::server]
      - recipe[postgresql::contrib]
      - recipe[postgresql::config_initdb]
      - recipe[postgresql::config_pgtune]
      - recipe[opennms::notemplates]
      - recipe[opennms::example_wallboard]
      - recipe[opennms::example_dashlet]
      - recipe[opennms::example_update_dashlet]
  - name: surveillance
    run_list:
      - recipe[java]
      - recipe[yum-centos::default]
      - recipe[yum-epel::default]
      - recipe[postgresql::client]
      - recipe[postgresql::server]
      - recipe[postgresql::contrib]
      - recipe[postgresql::config_initdb]
      - recipe[postgresql::config_pgtune]
      - recipe[opennms::notemplates]
      - recipe[opennms::example_surveillance_view]
  - name: send_event
    run_list:
      - recipe[java]
      - recipe[yum-centos::default]
      - recipe[yum-epel::default]
      - recipe[postgresql::client]
      - recipe[postgresql::server]
      - recipe[postgresql::contrib]
      - recipe[postgresql::config_initdb]
      - recipe[postgresql::config_pgtune]
      - recipe[opennms::notemplates]
      - recipe[opennms::example_send_event]
