source 'https://rubygems.org'

gem 'java-properties'
gem 'mdl'
# gem 'rest-client'
# gem 'rake', '~> 13.0'
# gem 'kitchen-inspec', '~> 1.1'
# gem 'cookstyle', '~> 3.0'
# gem 'stove', '~> 7'
# gem 'berkshelf', '~> 7.0'
# gem 'test-kitchen', '~> 1.25'
# gem 'inspec', '~> 3.9'
# gem 'kitchen-vagrant', '~> 1.7'
