# frozen_string_literal: true
source 'https://rubygems.org'

gem 'java_properties'
gem 'rest-client'
gem 'rake', '= 12.3.3'
gem 'rspec', '~> 3.7'
gem 'cucumber-tag_expressions', '~> 2.0', '>= 2.0.2'
gem 'kitchen-inspec', '~> 0.23'
gem 'cookstyle', '~> 2.1'
gem 'foodcritic', '~> 12.3'
gem 'stove', '~> 6'
gem 'berkshelf', '~> 6.3'
gem 'test-kitchen', '~> 1.20'
gem 'inspec', '~> 1.51'
gem 'kitchen-vagrant', '~> 1.6'
