name             'opennms'
maintainer       'David Schlenk'
maintainer_email 'dschlenk@onec1.com'
license          'Apache-2.0'
description      'Installs and Configures opennms and provides many useful custom resources.'
issues_url       'https://github.com/dschlenk/opennms-cookbook/issues'
source_url       'https://github.com/dschlenk/opennms-cookbook'
supports         'redhat', '>= 9.0'
supports         'rocky', '>= 9.0'
supports         'oracle', '>= 9.0'
supports         'centos', '>= 9.0'
version          '33.1.0'
depends          'postgresql'
chef_version '>= 18.5'
gem 'java-properties'
