version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2404:current
    steps:
      - checkout
      - run:
          name: install cinc workstation
          command: curl -L https://omnitruck.cinc.sh/install.sh | sudo bash -s -- -P cinc-workstation -v 24
      - run:
          name: rake
          command: chef exec rake

workflows:
  version: 2
  untagged-build:
    jobs:
      - test