version: 2.1

jobs:
  style:
    docker:
      - image: cincproject/workstation:25.13.7
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run:
          name: bundler
          command: cinc exec bundle install
      - run:
          name: mdl
          command: cinc exec mdl documentation/*.md
      - run:
          name: cookstyle
          command: cookstyle
  integration:
    machine:
      image: ubuntu-2404:current
    parallelism: 30
    steps:
      - checkout
      - run:
          name: docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run:
          name: install cinc workstation
          command: curl -L https://omnitruck.cinc.sh/install.sh | sudo bash -s -- -P cinc-workstation -v 25.13.7
      - run:
          name: cinc
          command: cinc shell-init bash
      - run:
          name: bundler
          command: cinc exec bundle install --prefer-local
      - run:
          name: kitchen
            # command: kitchen verify default
          command: kitchen list -b | circleci tests run --command="xargs -L 1 kitchen test -d always" --verbose
workflows:
  version: 2
  untagged-build:
    jobs:
      - style
      - integration
