version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2404:current
    steps:
      - checkout
      - run:
          name: install cinc workstation
          command: curl -L https://omnitruck.cinc.sh/install.sh | sudo bash -s -- -P cinc-workstation -v 24
      - run:
          name: cinc
          command: cinc shell-init bash
      - run:
          name: bundler
          command: cinc exec bundle install
      - run:
          name: cinc exec cookstyle
          command: cookstyle
      - run:
          name: cinc exec kitchen
          command: KITCHEN_LOCAL_YAML=kitchen.dokken.yml kitchen test default --destroy always

workflows:
  version: 2
  untagged-build:
    jobs:
      - test
