# yum repo stuff
default['yum']['opennms']['key_url']                      = "http://yum.opennms.org/OPENNMS-GPG-KEY"
default['yum']['opennms-stable-common']['baseurl']        = "http://yum.opennms.org/stable/common"
default['yum']['opennms-stable-common']['failovermethod'] = "roundrobin"
default['yum']['opennms-stable-rhel6']['baseurl']         = "http://yum.opennms.org/stable/rhel6"
default['yum']['opennms-stable-rhel6']['failovermethod']  = "roundrobin"

# opennms.conf
default['opennms']['conf']['home']           = "/opt/opennms"
default['opennms']['conf']['pidfile']        = "#{default['opennms']['conf']['home']}/logs/daemon/opennms.pid"
default['opennms']['conf']['logdir']         = "#{default['opennms']['conf']['home']}/logs/daemon"
default['opennms']['conf']['initdir']        = "#{default['opennms']['conf']['home']}/bin"
default['opennms']['conf']['redirect']       = "$LOG_DIRECTORY/output.log"
default['opennms']['conf']['start_timeout']  = 10
default['opennms']['conf']['status_wait']    = 5
default['opennms']['conf']['heap_size']      = 512
default['opennms']['conf']['addl_mgr_opts']  = ""
default['opennms']['conf']['addl_classpath'] = ""
default['opennms']['conf']['use_incgc']      = ""
default['opennms']['conf']['hotspot']        = ""
default['opennms']['conf']['verbose_gc']     = ""
default['opennms']['conf']['runjava_opts']   = ""
default['opennms']['conf']['invoke_url']     = "http://127.0.0.1:8181/invoke?objectname=OpenNMS:Name=Manager"
default['opennms']['conf']['runas']          = "root"
default['opennms']['conf']['max_file_descr'] = "20480"
default['opennms']['conf']['command']        = "8192"

# opennms.properties
# ICMP
default['opennms']['properties']['icmp']['pinger_class'] = "org.opennms.netmgt.icmp.jni6.Jni6Pinger"
default['opennms']['properties']['icmp']['require_v4']   = nil
default['opennms']['properties']['icmp']['require_v6']   = nil
# SNMP
default['opennms']['properties']['snmp']['strategy_class']             = nil
default['opennms']['properties']['snmp']['smisyntaxes']                = "opennms-snmp4j-smisyntaxes.properties"
default['opennms']['properties']['snmp']['forward_runtime_exceptions'] = false
default['opennms']['properties']['snmp']['log_factory']                = "org.snmp4j.log.Log4jLogFactory"
default['opennms']['properties']['snmp']['allow_64bit_ipaddress']      = true
# Data collection
default['opennms']['properties']['dc']['store_by_group']          = false
default['opennms']['properties']['dc']['store_by_foreign_source'] = false
default['opennms']['properties']['dc']['rrd_base_dir']            = "#{default['opennms']['conf']['home']}/share/rrd"
default['opennms']['properties']['dc']['rrd_dc_dir']              = "/snmp/"
default['opennms']['properties']['dc']['rrd_binary']              = "/usr/bin/rrdtool"
default['opennms']['properties']['dc']['decimal_format']          = nil
default['opennms']['properties']['dc']['reload_check_interval']   = nil
default['opennms']['properties']['dc']['instrumentation_class']   = nil
default['opennms']['properties']['dc']['enable_check_file_mod']   = nil
default['opennms']['properties']['dc']['force_rescan']            = nil
default['opennms']['properties']['dc']['instance_limiting']       = nil
# Remote
default['opennms']['properties']['remote']['rmi_server_hostname']      = nil
default['opennms']['properties']['remote']['exclude_service_monitors'] = "DHCP,NSClient,RadiusAuth,XMP"
default['opennms']['properties']['remote']['min_config_reload_int']    = nil
# Ticketing
default['opennms']['properties']['ticket']['servicelayer']  = "org.opennms.netmgt.ticketd.DefaultTicketerServiceLayer"
default['opennms']['properties']['ticket']['plugin']        = "org.opennms.netmgt.ticketd.NullTicketerPlugin"
default['opennms']['properties']['ticket']['enabled']       = nil
default['opennms']['properties']['ticket']['link_template'] = nil
# Misc
default['opennms']['properties']['misc']['layout_applications_vertically'] = false
default['opennms']['properties']['misc']['bin_dir']                        = "#{default['opennms']['conf']['home']}/bin"
default['opennms']['properties']['misc']['webapp_logs_dir']                = "#{default['opennms']['conf']['home']}/logs/webapp"
default['opennms']['properties']['misc']['headless']                       = true
default['opennms']['properties']['misc']['find_by_service_type_query']     = nil
default['opennms']['properties']['misc']['load_snmp_data_on_init']         = nil
default['opennms']['properties']['misc']['allow_html_fields']              = nil
# Reporting
default['opennms']['properties']['reporting']['template_dir']         = "#{default['opennms']['conf']['home']}/etc"
default['opennms']['properties']['reporting']['report_dir']           = "#{default['opennms']['conf']['home']}/share/reports"
default['opennms']['properties']['reporting']['report_logo']          = "#{default['opennms']['conf']['home']}/webapps/images/logo.gif"
default['opennms']['properties']['reporting']['ksc_graphs_per_line']  = 1
default['opennms']['properties']['reporting']['jasper_version']       = "3.7.6"
# Eventd IPC
default['opennms']['properties']['eventd']['proxy_host']     = nil
default['opennms']['properties']['eventd']['proxy_port']     = nil
default['opennms']['properties']['eventd']['proxy_timeout']  = nil
# RANCID
default['opennms']['properties']['rancid']['enabled']              = nil
default['opennms']['properties']['rancid']['only_rancid_adapter']  = nil
# RTC IPC
default['opennms']['properties']['rtc']['baseurl']   = "http://localhost:8980/opennms/rtc/post"
default['opennms']['properties']['rtc']['username']  = "rtc"
default['opennms']['properties']['rtc']['password']  = "rtc"
# MAP IPC
default['opennms']['properties']['map']['baseurl']   = "http://localhost:8980/opennms/map/post"
default['opennms']['properties']['map']['username']  = "map"
default['opennms']['properties']['map']['password']  = "map"
# JETTY
default['opennms']['properties']['jetty']['port']                   = 8980
default['opennms']['properties']['jetty']['ajp']                    = nil
default['opennms']['properties']['jetty']['host']                   = nil
default['opennms']['properties']['jetty']['max_form_content_size']  = nil
default['opennms']['properties']['jetty']['request_header_size']    = nil
default['opennms']['properties']['jetty']['max_form_keys']          = 2000
default['opennms']['properties']['jetty']['https_port']             = nil
default['opennms']['properties']['jetty']['https_host']             = nil
default['opennms']['properties']['jetty']['keystore']               = nil
default['opennms']['properties']['jetty']['ks_password']            = nil
default['opennms']['properties']['jetty']['key_password']           = nil
default['opennms']['properties']['jetty']['cert_alias']             = nil
default['opennms']['properties']['jetty']['exclude_cipher_suites']  = nil
default['opennms']['properties']['jetty']['https_baseurl']          = nil
# UI
default['opennms']['properties']['ui']['acls']                        = nil
default['opennms']['properties']['ui']['ack']                         = false
default['opennms']['properties']['ui']['show_count']                  = false
default['opennms']['properties']['ui']['show_outage_nodes']           = nil
default['opennms']['properties']['ui']['show_problem_nodes']          = nil
default['opennms']['properties']['ui']['outage_node_count']           = nil
default['opennms']['properties']['ui']['problem_node_count']          = nil
default['opennms']['properties']['ui']['show_node_status_bar']        = nil
default['opennms']['properties']['ui']['disable_login_success_event'] = nil
default['opennms']['properties']['ui']['center_url']                  = nil
# Asterisk AGI
default['opennms']['properties']['asterisk']['listen_address'] = nil
default['opennms']['properties']['asterisk']['listen_port']    = nil
default['opennms']['properties']['asterisk']['max_pool_size']  = nil
# Provisioning
default['opennms']['properties']['provisioning']['dns_server']                = "127.0.0.1"
default['opennms']['properties']['provisioning']['max_concurrent_xtn']        = nil
default['opennms']['properties']['provisioning']['enable_discovery']          = nil
default['opennms']['properties']['provisioning']['enable_deletions']          = nil
default['opennms']['properties']['provisioning']['schedule_existing_rescans'] = nil
default['opennms']['properties']['provisioning']['schedule_updated_rescans']  = nil
# SMS Gateway
default['opennms']['properties']['sms']['serial_ports']  = "/dev/ttyACM0:/dev/ttyACM1:/dev/ttyACM2:/dev/ttyACM3:/dev/ttyACM4:/dev/ttyACM5"
default['opennms']['properties']['sms']['polling']       = true
# Mapping / Geocoding
default['opennms']['properties']['geo']['map_type']       = "OpenLayers"
default['opennms']['properties']['geo']['api_key']        = ""
default['opennms']['properties']['geo']['geocoder_class'] = "org.opennms.features.poller.remote.gwt.server.geocoding.NullGeocoder"
default['opennms']['properties']['geo']['rate']           = 10
default['opennms']['properties']['geo']['referrer']       = "http://localhost/"
default['opennms']['properties']['geo']['min_quality']    = "ZIP"
default['opennms']['properties']['geo']['email']          = ""
default['opennms']['properties']['geo']['tile_url']       = "http://otile1.mqcdn.com/tiles/1.0.0/osm/${z}/${x}/${y}.png"
# access point monitor
default['opennms']['apm']['threads']           = 30
default['opennms']['apm']['pscan_interval']    = 1800000
default['opennms']['apm']['aruba_enabled']     = true
default['opennms']['apm']['moto_enabled']      = true
# database reports - availability
default['opennms']['db_reports']['avail']['cal']['logo']                    = "#{default['opennms']['conf']['home']}/etc/reports/logo.gif"
default['opennms']['db_reports']['avail']['cal']['endDate']['interval']     = "day"
default['opennms']['db_reports']['avail']['cal']['endDate']['count']        = 1
default['opennms']['db_reports']['avail']['cal']['endDate']['hours']        = 23
default['opennms']['db_reports']['avail']['cal']['endDate']['minutes']      = 59
default['opennms']['db_reports']['avail']['classic']['logo']                = "#{default['opennms']['conf']['home']}/etc/reports/logo.gif"
default['opennms']['db_reports']['avail']['classic']['endDate']['interval'] = "day"
default['opennms']['db_reports']['avail']['classic']['endDate']['count']    = 1
default['opennms']['db_reports']['avail']['classic']['endDate']['hours']    = 23
default['opennms']['db_reports']['avail']['classic']['endDate']['minutes']  = 59
# capsd-configuration.xml
default['opennms']['capsd']['rescan_frequency']     = 86400000
default['opennms']['capsd']['initial_sleep_time']   =  30000
default['opennms']['capsd']['max_suspect_threads']  = 6
default['opennms']['capsd']['max_rescan_threads']   = 3
default['opennms']['capsd']['icmp']['enabled']      = true
default['opennms']['capsd']['icmp']['scan']         = "on"
default['opennms']['capsd']['icmp']['timeout']      = 2000
default['opennms']['capsd']['icmp']['retry']        = 1
default['opennms']['capsd']['strafeping']['enabled'] = true
default['opennms']['capsd']['strafeping']['scan']    = "on"
default['opennms']['capsd']['strafeping']['timeout'] = 2000
default['opennms']['capsd']['strafeping']['retry']   = 1
default['opennms']['capsd']['snmp']['enabled'] = true
default['opennms']['capsd']['snmp']['scan']    = "on"
default['opennms']['capsd']['snmp']['timeout'] = 2000
default['opennms']['capsd']['snmp']['retry']   = 1
default['opennms']['capsd']['http']['enabled'] = true
default['opennms']['capsd']['http']['port']    = 80
default['opennms']['capsd']['http']['scan']    = "on"
default['opennms']['capsd']['http']['timeout'] = 3000
default['opennms']['capsd']['http']['retry']   = 1
default['opennms']['capsd']['http_8080']['enabled'] = true
default['opennms']['capsd']['http_8080']['port']    = 8080
default['opennms']['capsd']['http_8080']['scan']    = "on"
default['opennms']['capsd']['http_8080']['timeout'] = 3000
default['opennms']['capsd']['http_8080']['retry']   = 1
default['opennms']['capsd']['http_8000']['enabled'] = true
default['opennms']['capsd']['http_8000']['port']    = 8000
default['opennms']['capsd']['http_8000']['scan']    = "on"
default['opennms']['capsd']['http_8000']['timeout'] = 3000
default['opennms']['capsd']['http_8000']['retry']   = 1
default['opennms']['capsd']['https']['enabled'] = true
default['opennms']['capsd']['https']['port']    = 443
default['opennms']['capsd']['https']['scan']    = "on"
default['opennms']['capsd']['https']['timeout'] = 5000
default['opennms']['capsd']['https']['retry']   = 1
default['opennms']['capsd']['hyperic_agent']['enabled'] = true
default['opennms']['capsd']['hyperic_agent']['port']    = 2144
default['opennms']['capsd']['hyperic_agent']['scan']    = "on"
default['opennms']['capsd']['hyperic_agent']['timeout'] = 2000
default['opennms']['capsd']['hyperic_agent']['retry']   = 1
default['opennms']['capsd']['hyperichq']['enabled'] = true
default['opennms']['capsd']['hyperichq']['port']    = 7080
default['opennms']['capsd']['hyperichq']['scan']    = "off"
default['opennms']['capsd']['hyperichq']['timeout'] = 2000
default['opennms']['capsd']['hyperichq']['retry']   = 1
default['opennms']['capsd']['ftp']['enabled'] = true
default['opennms']['capsd']['ftp']['port']    = 21
default['opennms']['capsd']['ftp']['scan']    = "on"
default['opennms']['capsd']['ftp']['timeout'] = 2000
default['opennms']['capsd']['ftp']['retry']   = 1
default['opennms']['capsd']['telnet']['enabled'] = true
default['opennms']['capsd']['telnet']['banner']  = "*"
default['opennms']['capsd']['telnet']['port']    = 23
default['opennms']['capsd']['telnet']['scan']    = "on"
default['opennms']['capsd']['telnet']['timeout'] = 3000
default['opennms']['capsd']['telnet']['retry']   = 1
default['opennms']['capsd']['dns']['enabled'] = true
default['opennms']['capsd']['dns']['lookup']  = "localhost"
default['opennms']['capsd']['dns']['port']    = 53
default['opennms']['capsd']['dns']['scan']    = "on"
default['opennms']['capsd']['dns']['timeout'] = 5000
default['opennms']['capsd']['dns']['retry']   = 1
default['opennms']['capsd']['imap']['enabled'] = true
default['opennms']['capsd']['imap']['port']    = 143
default['opennms']['capsd']['imap']['scan']    = "on"
default['opennms']['capsd']['imap']['timeout'] = 3000
default['opennms']['capsd']['imap']['retry']   = 1
default['opennms']['capsd']['msexchange']['enabled']   = true
default['opennms']['capsd']['msexchange']['pop3_port'] = 110
default['opennms']['capsd']['msexchange']['imap_port'] = 143
default['opennms']['capsd']['msexchange']['mapi_port'] = 593
default['opennms']['capsd']['msexchange']['scan']      = "on"
default['opennms']['capsd']['msexchange']['timeout']   = 3000
default['opennms']['capsd']['msexchange']['retry']     = 1
default['opennms']['capsd']['smtp']['enabled'] = true
default['opennms']['capsd']['smtp']['port']    = 25
default['opennms']['capsd']['smtp']['scan']    = "on"
default['opennms']['capsd']['smtp']['timeout'] = 3000
default['opennms']['capsd']['smtp']['retry']   = 1
default['opennms']['capsd']['pop3']['enabled'] = true
default['opennms']['capsd']['pop3']['port']    = 110
default['opennms']['capsd']['pop3']['scan']    = "on"
default['opennms']['capsd']['pop3']['timeout'] = 3000
default['opennms']['capsd']['pop3']['retry']   = 1
default['opennms']['capsd']['ssh']['enabled'] = true
default['opennms']['capsd']['ssh']['port']    = 22
default['opennms']['capsd']['ssh']['banner']  = "SSH"
default['opennms']['capsd']['ssh']['scan']    = "on"
default['opennms']['capsd']['ssh']['timeout'] = 3000
default['opennms']['capsd']['ssh']['retry'] = 1
default['opennms']['capsd']['mysql']['enabled'] = true
default['opennms']['capsd']['mysql']['port']    = 3306
default['opennms']['capsd']['mysql']['banner']  = "*"
default['opennms']['capsd']['mysql']['scan']    = "on"
default['opennms']['capsd']['mysql']['timeout'] = 3000
default['opennms']['capsd']['mysql']['retry']   = 1
default['opennms']['capsd']['sqlserver']['enabled'] = true
default['opennms']['capsd']['sqlserver']['port']    = 1433
default['opennms']['capsd']['sqlserver']['banner']  = "*"
default['opennms']['capsd']['sqlserver']['scan']    = "on"
default['opennms']['capsd']['sqlserver']['timeout'] = 3000
default['opennms']['capsd']['sqlserver']['retry']   = 1
default['opennms']['capsd']['oracle']['enabled'] = true
default['opennms']['capsd']['oracle']['port']    = 1521
default['opennms']['capsd']['oracle']['banner']  = "*"
default['opennms']['capsd']['oracle']['scan']    = "on"
default['opennms']['capsd']['oracle']['timeout'] = 3000
default['opennms']['capsd']['oracle']['retry']   = 1
default['opennms']['capsd']['postgres']['enabled'] = true
default['opennms']['capsd']['postgres']['port']    = 5432
default['opennms']['capsd']['postgres']['banner']  = "*"
default['opennms']['capsd']['postgres']['scan']    = "on"
default['opennms']['capsd']['postgres']['timeout'] = 3000
default['opennms']['capsd']['postgres']['retry']   = 1
default['opennms']['capsd']['router']['enabled'] = true
default['opennms']['capsd']['router']['vbname']  = ".1.3.6.1.2.1.4.1.0"
default['opennms']['capsd']['router']['vbvalue'] = 1
default['opennms']['capsd']['router']['scan']    = "on"
default['opennms']['capsd']['router']['timeout'] = 2000
default['opennms']['capsd']['router']['retry']   = 1
default['opennms']['capsd']['hp_insight_manager']['enabled'] = true
default['opennms']['capsd']['hp_insight_manager']['banner']  = "*"
default['opennms']['capsd']['hp_insight_manager']['port']    = 2381
default['opennms']['capsd']['hp_insight_manager']['scan']    = "on"
default['opennms']['capsd']['hp_insight_manager']['timeout'] = 3000
default['opennms']['capsd']['hp_insight_manager']['retry']   = 1
default['opennms']['capsd']['dell_openmanage']['enabled'] = true
default['opennms']['capsd']['dell_openmanage']['banner']  = "*"
default['opennms']['capsd']['dell_openmanage']['port']    = 1311
default['opennms']['capsd']['dell_openmanage']['scan']    = "on"
default['opennms']['capsd']['dell_openmanage']['timeout'] = 3000
default['opennms']['capsd']['dell_openmanage']['retry']   = 1
default['opennms']['capsd']['nrpe']['enabled'] = true
default['opennms']['capsd']['nrpe']['banner']  = "*"
default['opennms']['capsd']['nrpe']['command'] = "_NRPE_CHECK"
default['opennms']['capsd']['nrpe']['port']    = 5666
default['opennms']['capsd']['nrpe']['scan']    = "on"
default['opennms']['capsd']['nrpe']['timeout'] = 3000
default['opennms']['capsd']['nrpe']['retry']   = 2
default['opennms']['capsd']['nrpe_nossl']['enabled'] = true
default['opennms']['capsd']['nrpe_nossl']['banner']  = "*"
default['opennms']['capsd']['nrpe_nossl']['command'] = "_NRPE_CHECK"
default['opennms']['capsd']['nrpe_nossl']['usessl']  = false
default['opennms']['capsd']['nrpe_nossl']['port']    = 5666
default['opennms']['capsd']['nrpe_nossl']['scan']    = "on"
default['opennms']['capsd']['nrpe_nossl']['timeout'] = 3000
default['opennms']['capsd']['nrpe_nossl']['retry']   = 2
default['opennms']['capsd']['windows_task_scheduler']['enabled'] = true
default['opennms']['capsd']['windows_task_scheduler']['service_name']  = "Task Scheduler"
default['opennms']['capsd']['windows_task_scheduler']['scan']    = "on"
default['opennms']['capsd']['windows_task_scheduler']['timeout'] = 2000
default['opennms']['capsd']['windows_task_scheduler']['retry']   = 1
default['opennms']['capsd']['opennms_jvm']['enabled']  = true
default['opennms']['capsd']['opennms_jvm']['port']     = 18980
default['opennms']['capsd']['opennms_jvm']['factory']  = "PASSWORD-CLEAR"
default['opennms']['capsd']['opennms_jvm']['username'] = "admin"
default['opennms']['capsd']['opennms_jvm']['password'] = "admin"
default['opennms']['capsd']['opennms_jvm']['protocol'] = "rmi"
default['opennms']['capsd']['opennms_jvm']['url_path'] = "/jmxrmi"
default['opennms']['capsd']['opennms_jvm']['scan']     = "on"
default['opennms']['capsd']['opennms_jvm']['timeout']  = 3000
default['opennms']['capsd']['opennms_jvm']['retry']    = 2
default['opennms']['capsd']['opennms_jvm']['type']     = "default"
# categories.xml
default['opennms']['categories']['common_rule']        = "IPADDR != '0.0.0.0'"
default['opennms']['categories']['overall']['enable']   = true
default['opennms']['categories']['overall']['label']    = "Overall Service Availability"
default['opennms']['categories']['overall']['comment']  = "This category reflects availability of all services currently being monitored by OpenNMS."
default['opennms']['categories']['overall']['normal']   = 99.99
default['opennms']['categories']['overall']['warning']  = 97
default['opennms']['categories']['overall']['services'] = []
default['opennms']['categories']['overall']['rule']     = "IPADDR != '0.0.0.0'"
default['opennms']['categories']['interfaces']['enable']   = true
default['opennms']['categories']['interfaces']['label']    = "Network Interfaces"
default['opennms']['categories']['interfaces']['comment']  = "This category reflects the ability to 'ping' managed devices and SNMP agents.  'Ping', using the ICMP protocol, tests a devices network connectivity/availability."
default['opennms']['categories']['interfaces']['normal']   = 99.99
default['opennms']['categories']['interfaces']['warning']  = 97
default['opennms']['categories']['interfaces']['services'] = ["ICMP,SNMP"]
default['opennms']['categories']['interfaces']['rule']     = "isICMP | isSNMP) & (IPADDR != '0.0.0.0')"
default['opennms']['categories']['email']['enable']   = true
default['opennms']['categories']['email']['label']    = "Email Servers"
default['opennms']['categories']['email']['comment']  = "This category includes all managed interfaces which are running an Email service, including SMTP, POP3, or IMAP.  This will include MS Exchange servers running these protocols."
default['opennms']['categories']['email']['normal']   = 99.99
default['opennms']['categories']['email']['warning']  = 97
default['opennms']['categories']['email']['services'] = ["SMTP","POP3","IMAP"]
default['opennms']['categories']['email']['rule']     = "isSMTP | isPOP3 | isIMAP"
default['opennms']['categories']['web']['enable']   = true
default['opennms']['categories']['web']['label']    = "Web Servers"
default['opennms']['categories']['web']['comment']  = "This category includes all managed interfaces which are running an HTTP (Web) server on port 80 or other common ports."
default['opennms']['categories']['web']['normal']   = 99.99
default['opennms']['categories']['web']['warning']  = 97
default['opennms']['categories']['web']['services'] = ["HTTP","HTTPS","HTTP-8000","HTTP-8080"]
default['opennms']['categories']['web']['rule']     = "isHTTP | isHTTPS | isHTTP-8000 | isHTTP-8080"
default['opennms']['categories']['jmx']['enable']   = true
default['opennms']['categories']['jmx']['label']    = "JMX Servers"
default['opennms']['categories']['jmx']['comment']  = "This category includes all managed interfaces which are running JMX servers."
default['opennms']['categories']['jmx']['normal']   = 99.99
default['opennms']['categories']['jmx']['warning']  = 97
default['opennms']['categories']['jmx']['services'] = ["JBoss4","JBoss32","JVM"]
default['opennms']['categories']['jmx']['rule']     = "isJBoss4 | isJBoss32 | isJVM"
default['opennms']['categories']['dns']['enable']   = true
default['opennms']['categories']['dns']['label']    = "DNS and DHCP Servers"
default['opennms']['categories']['dns']['comment']  = "This category includes all managed interfaces which are running either DNS (name resolution) servers or DHCP servers."
default['opennms']['categories']['dns']['normal']   = 99.99
default['opennms']['categories']['dns']['warning']  = 97
default['opennms']['categories']['dns']['services'] = ["DNS","DHCP"]
default['opennms']['categories']['dns']['rule']     = "isDNS | isDHCP"
default['opennms']['categories']['db']['enable']   = true
default['opennms']['categories']['db']['label']    = "Database Servers"
default['opennms']['categories']['db']['comment']  = "This category includes all managed interfaces which are currently running PostgreSQL, MySQL, SQLServer, or Oracle database servers."
default['opennms']['categories']['db']['normal']   = 99.99
default['opennms']['categories']['db']['warning']  = 97
default['opennms']['categories']['db']['services'] = ["MySQL","Oracle","Postgres","SQLServer"]
default['opennms']['categories']['db']['rule']     = "isMySQL | isOracle | isPostgres | isSQLServer"
default['opennms']['categories']['other']['enable']   = true
default['opennms']['categories']['other']['label']    = "Other Servers"
default['opennms']['categories']['other']['comment']  = "This category includes all managed interfaces which are running FTP (file transfer protocol) servers or SSH (secure shell) servers."
default['opennms']['categories']['other']['normal']   = 99.99
default['opennms']['categories']['other']['warning']  = 97
default['opennms']['categories']['other']['services'] = ["FTP","SSH"]
default['opennms']['categories']['other']['rule']     = "isFTP | isSSH"
default['opennms']['categories']['inet']['enable']   = true
default['opennms']['categories']['inet']['label']    = "Internet Connectivity"
default['opennms']['categories']['inet']['comment']  = "This category reflects the ability to 'ping' the router at the ISP-end of your Internet connection."
default['opennms']['categories']['inet']['normal']   = 99.99
default['opennms']['categories']['inet']['warning']  = 97
default['opennms']['categories']['inet']['services'] = ["ICMP"]
default['opennms']['categories']['inet']['rule']     = "ipaddr == '0.0.0.0'"
# chart-configuration.xml
default['opennms']['chart']['severity_enable']  = true
default['opennms']['chart']['outages_enable']   = true
default['opennms']['chart']['inventory_enable'] = true
# collectd-configuration.xml
default['opennms']['collectd']['threads'] = 50
default['opennms']['collectd']['vmware3']['enabled']                     = true
default['opennms']['collectd']['vmware3']['filter']                      = "(IPADDR != '0.0.0.0') & (categoryName == 'VMware3')"
default['opennms']['collectd']['vmware3']['service']['vm']['enabled']    = true
default['opennms']['collectd']['vmware3']['service']['vm']['interval']   = 300000
default['opennms']['collectd']['vmware3']['service']['vm']['status']     = "on"
default['opennms']['collectd']['vmware3']['service']['vm']['collection'] = "default-VirtualMachine3"
default['opennms']['collectd']['vmware3']['service']['vm']['threshold']  = true
default['opennms']['collectd']['vmware3']['service']['host']['enabled']    = true
default['opennms']['collectd']['vmware3']['service']['host']['interval']   = 300000
default['opennms']['collectd']['vmware3']['service']['host']['status']     = "on"
default['opennms']['collectd']['vmware3']['service']['host']['collection'] = "default-HostSystem3"
default['opennms']['collectd']['vmware3']['service']['host']['threshold']  = true
default['opennms']['collectd']['vmware3']['service']['cim_host']['enabled']    = true
default['opennms']['collectd']['vmware3']['service']['cim_host']['interval']   = 300000
default['opennms']['collectd']['vmware3']['service']['cim_host']['status']     = "on"
default['opennms']['collectd']['vmware3']['service']['cim_host']['collection'] = "default-ESX-HostSystem"
default['opennms']['collectd']['vmware3']['service']['cim_host']['threshold']  = true
default['opennms']['collectd']['vmware4']['enabled']                     = true
default['opennms']['collectd']['vmware4']['filter']                      = "(IPADDR != '0.0.0.0') & (categoryName == 'VMware4')"
default['opennms']['collectd']['vmware4']['service']['vm']['enabled']    = true
default['opennms']['collectd']['vmware4']['service']['vm']['interval']   = 300000
default['opennms']['collectd']['vmware4']['service']['vm']['status']     = "on"
default['opennms']['collectd']['vmware4']['service']['vm']['collection'] = "default-VirtualMachine4"
default['opennms']['collectd']['vmware4']['service']['vm']['threshold']  = true
default['opennms']['collectd']['vmware4']['service']['host']['enabled']    = true
default['opennms']['collectd']['vmware4']['service']['host']['interval']   = 300000
default['opennms']['collectd']['vmware4']['service']['host']['status']     = "on"
default['opennms']['collectd']['vmware4']['service']['host']['collection'] = "default-HostSystem4"
default['opennms']['collectd']['vmware4']['service']['host']['threshold']  = true
default['opennms']['collectd']['vmware4']['service']['cim_host']['enabled']    = true
default['opennms']['collectd']['vmware4']['service']['cim_host']['interval']   = 300000
default['opennms']['collectd']['vmware4']['service']['cim_host']['status']     = "on"
default['opennms']['collectd']['vmware4']['service']['cim_host']['collection'] = "default-ESX-HostSystem"
default['opennms']['collectd']['vmware4']['service']['cim_host']['threshold']  = true
default['opennms']['collectd']['vmware4']['enabled']                     = true
default['opennms']['collectd']['vmware5']['filter']                      = "(IPADDR != '0.0.0.0') & (categoryName == 'VMware5')"
default['opennms']['collectd']['vmware5']['service']['vm']['enabled']    = true
default['opennms']['collectd']['vmware5']['service']['vm']['interval']   = 300000
default['opennms']['collectd']['vmware5']['service']['vm']['status']     = "on"
default['opennms']['collectd']['vmware5']['service']['vm']['collection'] = "default-VirtualMachine5"
default['opennms']['collectd']['vmware5']['service']['vm']['threshold']  = true
default['opennms']['collectd']['vmware5']['service']['host']['enabled']    = true
default['opennms']['collectd']['vmware5']['service']['host']['interval']   = 300000
default['opennms']['collectd']['vmware5']['service']['host']['status']     = "on"
default['opennms']['collectd']['vmware5']['service']['host']['collection'] = "default-HostSystem5"
default['opennms']['collectd']['vmware5']['service']['host']['threshold']  = true
default['opennms']['collectd']['vmware5']['service']['cim_host']['enabled']    = true
default['opennms']['collectd']['vmware5']['service']['cim_host']['interval']   = 300000
default['opennms']['collectd']['vmware5']['service']['cim_host']['status']     = "on"
default['opennms']['collectd']['vmware5']['service']['cim_host']['collection'] = "default-ESX-HostSystem"
default['opennms']['collectd']['vmware5']['service']['cim_host']['threshold']  = true
default['opennms']['collectd']['vmware5']['enabled'] = nil
default['opennms']['collectd']['example1']['enabled']                      = true
default['opennms']['collectd']['example1']['filter']                       = "IPADDR != '0.0.0.0'"
default['opennms']['collectd']['example1']['ipv4_range']['begin']          = "1.1.1.1"
default['opennms']['collectd']['example1']['ipv4_range']['end']            = "254.254.254.254"
default['opennms']['collectd']['example1']['ipv6_range']['begin']          = "::1"
default['opennms']['collectd']['example1']['ipv6_range']['end']            = "ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff"
default['opennms']['collectd']['example1']['service']['snmp']['enabled']     = true
default['opennms']['collectd']['example1']['service']['snmp']['interval']   = 300000
default['opennms']['collectd']['example1']['service']['snmp']['status']     = "on"
default['opennms']['collectd']['example1']['service']['snmp']['collection'] = "default"
default['opennms']['collectd']['example1']['service']['snmp']['threshold']  = true
default['opennms']['collectd']['example1']['service']['wmi']['enabled']     = true
default['opennms']['collectd']['example1']['service']['wmi']['interval']   = 300000
default['opennms']['collectd']['example1']['service']['wmi']['status']     = "off"
default['opennms']['collectd']['example1']['service']['wmi']['collection'] = "default"
default['opennms']['collectd']['example1']['service']['wmi']['threshold']  = true
default['opennms']['collectd']['example1']['service']['opennms_jvm']['enabled']        = true
default['opennms']['collectd']['example1']['service']['opennms_jvm']['interval']      = 300000
default['opennms']['collectd']['example1']['service']['opennms_jvm']['status']        = "on"
default['opennms']['collectd']['example1']['service']['opennms_jvm']['port']          = 18980
default['opennms']['collectd']['example1']['service']['opennms_jvm']['retry']         = 2
default['opennms']['collectd']['example1']['service']['opennms_jvm']['timeout']       = 3000
default['opennms']['collectd']['example1']['service']['opennms_jvm']['protocol']      = "rmi"
default['opennms']['collectd']['example1']['service']['opennms_jvm']['url_path']      = "/jmxrmi"
default['opennms']['collectd']['example1']['service']['opennms_jvm']['rrd_base_name'] = "java"
default['opennms']['collectd']['example1']['service']['opennms_jvm']['ds_name']       = "opennms-java"
default['opennms']['collectd']['example1']['service']['opennms_jvm']['friendly_name'] = "opennms-java"
default['opennms']['collectd']['example1']['service']['opennms_jvm']['collection']    = "jsr160"
default['opennms']['collectd']['example1']['service']['opennms_jvm']['threshold']     = true
default['opennms']['collectd']['example1']['service']['postgresql']['enabled']     = true
default['opennms']['collectd']['example1']['service']['postgresql']['interval']   = 300000
default['opennms']['collectd']['example1']['service']['postgresql']['status']     = "on"
default['opennms']['collectd']['example1']['service']['postgresql']['collection'] = "PostgreSQL"
default['opennms']['collectd']['example1']['service']['postgresql']['threshold']  = true
default['opennms']['collectd']['example1']['service']['postgresql']['driver']     = "org.postgresql.Driver"
default['opennms']['collectd']['example1']['service']['postgresql']['user']       = "postgres"
default['opennms']['collectd']['example1']['service']['postgresql']['password']   = "postgres"
default['opennms']['collectd']['example1']['service']['postgresql']['url']        = "jdbc:postgresql://OPENNMS_JDBC_HOSTNAME:5432/opennms"
# Data Collection
default['opennms']['datacollection']['default']['enabled']          = true
default['opennms']['datacollection']['default']['snmpStorageFlag']  = "select"
default['opennms']['datacollection']['default']['rrd']['step']      = 300
default['opennms']['datacollection']['default']['rrd']['rras']      = ["RRA:AVERAGE:0.5:1:2016","RRA:AVERAGE:0.5:12:1488","RRA:AVERAGE:0.5:288:366","RRA:MAX:0.5:288:366","RRA:MIN:0.5:288:366"]
default['opennms']['datacollection']['default']['mib2']             = true
default['opennms']['datacollection']['default']['threecom']         = true
default['opennms']['datacollection']['default']['acme']             = true
default['opennms']['datacollection']['default']['akcp']             = true
default['opennms']['datacollection']['default']['alvarion']         = true
default['opennms']['datacollection']['default']['apc']              = true
default['opennms']['datacollection']['default']['ascend']           = true
default['opennms']['datacollection']['default']['asterisk']         = true
default['opennms']['datacollection']['default']['bluecat']          = true
default['opennms']['datacollection']['default']['bluecoat']         = true
default['opennms']['datacollection']['default']['brocade']          = true
default['opennms']['datacollection']['default']['checkpoint']       = true
default['opennms']['datacollection']['default']['cisco']            = true
default['opennms']['datacollection']['default']['clavister']        = true
default['opennms']['datacollection']['default']['colubris']         = true
default['opennms']['datacollection']['default']['concord']          = true
default['opennms']['datacollection']['default']['cyclades']         = true
default['opennms']['datacollection']['default']['dell']             = true
default['opennms']['datacollection']['default']['ericsson']         = true
default['opennms']['datacollection']['default']['equallogic']       = true
default['opennms']['datacollection']['default']['extreme']          = true
default['opennms']['datacollection']['default']['f5']               = true
default['opennms']['datacollection']['default']['fortinet']         = true
default['opennms']['datacollection']['default']['force10']          = true
default['opennms']['datacollection']['default']['foundry']          = true
default['opennms']['datacollection']['default']['hp']               = true
default['opennms']['datacollection']['default']['hwg']              = true
default['opennms']['datacollection']['default']['ibm']              = true
default['opennms']['datacollection']['default']['ipunity']          = true
default['opennms']['datacollection']['default']['juniper']          = true
default['opennms']['datacollection']['default']['kyocera']          = true
default['opennms']['datacollection']['default']['lexmark']          = true
default['opennms']['datacollection']['default']['liebert']          = true
default['opennms']['datacollection']['default']['makelsan']         = true
default['opennms']['datacollection']['default']['mge']              = true
default['opennms']['datacollection']['default']['microsoft']        = true
default['opennms']['datacollection']['default']['mikrotik']         = true
default['opennms']['datacollection']['default']['netapp']           = true
default['opennms']['datacollection']['default']['netbotz']          = true
default['opennms']['datacollection']['default']['netenforcer']      = true
default['opennms']['datacollection']['default']['netscaler']        = true
default['opennms']['datacollection']['default']['netsnmp']          = true
default['opennms']['datacollection']['default']['nortel']           = true
default['opennms']['datacollection']['default']['novell']           = true
default['opennms']['datacollection']['default']['pfsense']          = true
default['opennms']['datacollection']['default']['powerware']        = true
default['opennms']['datacollection']['default']['postgres']         = true
default['opennms']['datacollection']['default']['riverbed']         = true
default['opennms']['datacollection']['default']['savin']            = true
default['opennms']['datacollection']['default']['servertech']       = true
default['opennms']['datacollection']['default']['sofaware']         = true
default['opennms']['datacollection']['default']['sun']              = true
default['opennms']['datacollection']['default']['trango']           = true
default['opennms']['datacollection']['default']['wmi']              = true
default['opennms']['datacollection']['default']['xmp']              = true
default['opennms']['datacollection']['default']['zeus']             = true
default['opennms']['datacollection']['default']['vmware3']          = true
default['opennms']['datacollection']['default']['vmware4']          = true
default['opennms']['datacollection']['default']['vmware5']          = true
default['opennms']['datacollection']['default']['vmwarecim']        = true
default['opennms']['datacollection']['ejn']['enabled']          = true
default['opennms']['datacollection']['ejn']['snmpStorageFlag']  = "select"
default['opennms']['datacollection']['ejn']['rrd']['step']      = 180
default['opennms']['datacollection']['ejn']['rrd']['rras']      = ["RRA:AVERAGE:0.5:1:3360","RRA:AVERAGE:0.5:20:1488","RRA:AVERAGE:0.5:480:366","RRA:MAX:0.5:480:366","RRA:MIN:0.5:480:366"]
default['opennms']['datacollection']['ejn']['rrd']['rras']      = ["RRA:AVERAGE:0.5:1:3360","RRA:AVERAGE:0.5:20:1488","RRA:AVERAGE:0.5:480:366","RRA:MAX:0.5:480:366","RRA:MIN:0.5:480:366"]
# discovery-configuration.xml
default['opennms']['discovery']['threads']          = 1
default['opennms']['discovery']['pps']              = 1
default['opennms']['discovery']['init_sleep_ms']    = 30000
default['opennms']['discovery']['restart_sleep_ms'] = 86400000
default['opennms']['discovery']['retries']          = 1
default['opennms']['discovery']['timeout']          = 2000
# eventd-configuration.xml
default['opennms']['eventd']['tcp_address']            = "127.0.0.1"
default['opennms']['eventd']['tcp_port']               = 5817
default['opennms']['eventd']['udp_address']            = "127.0.0.1"
default['opennms']['eventd']['udp_port']               = 5817
default['opennms']['eventd']['receivers']              = 5
default['opennms']['eventd']['get_next_eventid']       = "SELECT nextval('eventsNxtId')"
default['opennms']['eventd']['sock_so_timeout_req']    = true
default['opennms']['eventd']['socket_so_timeout_period'] = 3000
# events-archiver-configuration.xml
default['opennms']['events_archiver']['age']        = "7d"
default['opennms']['events_archiver']['separator'] = "#"
# javamail-configuration.properties
default['opennms']['javamail_props']['from_address']          = nil
default['opennms']['javamail_props']['mail_host']             = nil
default['opennms']['javamail_props']['mailer']                = nil
default['opennms']['javamail_props']['transport']             = nil
default['opennms']['javamail_props']['debug']                 = nil
default['opennms']['javamail_props']['smtpport']              = nil
default['opennms']['javamail_props']['smtpssl']               = nil
default['opennms']['javamail_props']['quitwait']              = nil
default['opennms']['javamail_props']['use_JMTA']              = nil
default['opennms']['javamail_props']['authenticate']          = nil
default['opennms']['javamail_props']['authenticate_user']     = nil
default['opennms']['javamail_props']['authenticate_password'] = nil
default['opennms']['javamail_props']['starttls']              = nil
default['opennms']['javamail_props']['message_content_type']  = nil
default['opennms']['javamail_props']['charset']               = nil
# javamail-configuration.xml
default['opennms']['javamail_config']['default_read_config_name'] = "localhost"
default['opennms']['javamail_config']['default_send_config_name'] = "localhost"
default['opennms']['javamail_config']['default_read']['attempt_interval'] = 1000
default['opennms']['javamail_config']['default_read']['delete_all_mail']  = false
default['opennms']['javamail_config']['default_read']['mail_folder']      = "INBOX"
default['opennms']['javamail_config']['default_read']['debug']            = true
default['opennms']['javamail_config']['default_read']['properties']       = {'mail.pop3.apop.enable' => false, 'mail.pop3.rsetbeforequit' => false}
default['opennms']['javamail_config']['default_read']['host']             = "127.0.0.1"
default['opennms']['javamail_config']['default_read']['port']             = 110
default['opennms']['javamail_config']['default_read']['ssl_enable']       = false
default['opennms']['javamail_config']['default_read']['start_tls']        = false
default['opennms']['javamail_config']['default_read']['transport']        = "pop3"
default['opennms']['javamail_config']['default_read']['user']             = "opennms"
default['opennms']['javamail_config']['default_read']['password']         = "opennms"
default['opennms']['javamail_config']['default_send']['attempt_interval']   = 3000
default['opennms']['javamail_config']['default_send']['use_authentication'] = false
default['opennms']['javamail_config']['default_send']['use_jmta']           = true
default['opennms']['javamail_config']['default_send']['debug']              = true
default['opennms']['javamail_config']['default_send']['host']               = "127.0.0.1"
default['opennms']['javamail_config']['default_send']['port']               = 25
default['opennms']['javamail_config']['default_send']['char_set']           = "us-ascii"
default['opennms']['javamail_config']['default_send']['mailer']             = "smtpsend"
default['opennms']['javamail_config']['default_send']['content_type']       = "text/plain"
default['opennms']['javamail_config']['default_send']['encoding']           = "7-bit"
default['opennms']['javamail_config']['default_send']['quit_wait']          = true
default['opennms']['javamail_config']['default_send']['ssl_enable']         = false
default['opennms']['javamail_config']['default_send']['start_tls']          = false
default['opennms']['javamail_config']['default_send']['transport']          = "smtp"
default['opennms']['javamail_config']['default_send']['to']                 = "root@localhost"
default['opennms']['javamail_config']['default_send']['from']               = "root@[127.0.0.1]"
default['opennms']['javamail_config']['default_send']['subject']            = "OpenNMS Test Message"
default['opennms']['javamail_config']['default_send']['body']               = "This is an OpenNMS test message."
default['opennms']['javamail_config']['default_send']['user']               = "opennms"
default['opennms']['javamail_config']['default_send']['password']           = "opennms"
# jcifs.properties
default['opennms']['jcifs']['loglevel']      = 1
default['opennms']['jcifs']['wins']          = nil
default['opennms']['jcifs']['lmhosts']       = nil
default['opennms']['jcifs']['resolve_order'] = nil
default['opennms']['jcifs']['hostname']      = nil
default['opennms']['jcifs']['retry_count']   = nil
default['opennms']['jcifs']['username']      = nil
default['opennms']['jcifs']['password']      = nil
default['opennms']['jcifs']['client_laddr']  = nil
# jdbc-datacollection-config.xml
default['opennms']['jdbc_dc']['enable_default']     = true
default['opennms']['jdbc_dc']['enable_mysql_stats'] = true
default['opennms']['jdbc_dc']['enable_pgsql_stats'] = true
# jmx-datacollection-config.xml
default['opennms']['jmx_dc']['enable_jboss']        = true
default['opennms']['jmx_dc']['enable_opennms']      = true
# linkd-configuration.xml
default['opennms']['linkd']['threads']                      = 5
default['opennms']['linkd']['initial_sleep_time']           = 3600000
default['opennms']['linkd']['snmp_poll_interval']           = 18000000
default['opennms']['linkd']['discovery_link_interval']      = 1800000
default['opennms']['linkd']['package']                      = "example1"
default['opennms']['linkd']['filter']                       = "IPADDR != '0.0.0.0'"
default['opennms']['linkd']['range_begin']                  = "1.1.1.1"
default['opennms']['linkd']['range_end']                    = "254.254.254.254"
default['opennms']['linkd']['iproutes']['enable_netscreen'] = true
default['opennms']['linkd']['iproutes']['enable_cisco']     = true
default['opennms']['linkd']['iproutes']['enable_darwin']    = true
default['opennms']['linkd']['vlan']['enable_3com']          = true
default['opennms']['linkd']['vlan']['enable_3com3870']      = true
default['opennms']['linkd']['vlan']['enable_nortel']        = true
default['opennms']['linkd']['vlan']['enable_intel']         = true
default['opennms']['linkd']['vlan']['enable_hp']            = true
default['opennms']['linkd']['vlan']['enable_cisco']         = true
default['opennms']['linkd']['vlan']['enable_extreme']       = true
# log4j.properties
# each is a hash with possible keys being level, appender, max_file_size, max_backup_index, file, layout, conversion_pattern
default['opennms']['log4j']['stds']                = {}
default['opennms']['log4j']['uncategorized']       = {}
default['opennms']['log4j']['misc']                = {}
default['opennms']['log4j']['hibernate']           = {}
default['opennms']['log4j']['spring']              = {}
default['opennms']['log4j']['provisiond']          = {}
default['opennms']['log4j']['pinger']              = {}
default['opennms']['log4j']['reportd']             = {}
default['opennms']['log4j']['ticketer']            = {}
default['opennms']['log4j']['eventd']              = {}
default['opennms']['log4j']['alarmd']              = {}
default['opennms']['log4j']['ackd']                = {}
default['opennms']['log4j']['discovery']           = {}
default['opennms']['log4j']['capsd']               = {}
default['opennms']['log4j']['notifd']              = {}
default['opennms']['log4j']['poller']              = {}
default['opennms']['log4j']['snmpinterfacepoller'] = {}
default['opennms']['log4j']['collectd']            = {}
default['opennms']['log4j']['correlation']         = {}
default['opennms']['log4j']['drools']              = {}
default['opennms']['log4j']['passive']             = {}
default['opennms']['log4j']['threshd']             = {}
default['opennms']['log4j']['trapd']               = {}
default['opennms']['log4j']['actiond']             = {}
default['opennms']['log4j']['scriptd']             = {}
default['opennms']['log4j']['rtc']                 = {}
default['opennms']['log4j']['rtcdata']             = {}
default['opennms']['log4j']['outage']              = {}
default['opennms']['log4j']['translator']          = {}
default['opennms']['log4j']['vacuum']              = {}
default['opennms']['log4j']['manager']             = {}
default['opennms']['log4j']['queued']              = {}
default['opennms']['log4j']['jetty']               = {}
default['opennms']['log4j']['web']                 = {}
default['opennms']['log4j']['webauth']             = {}
default['opennms']['log4j']['web_rtc']             = {}
default['opennms']['log4j']['tomcat_internal']     = {}
default['opennms']['log4j']['dhcpd']               = {}
default['opennms']['log4j']['vulnscand']           = {}
default['opennms']['log4j']['syslogd']             = {}
default['opennms']['log4j']['xmlrpcd']             = {}
default['opennms']['log4j']['report']              = {}
default['opennms']['log4j']['vmware']              = {}
default['opennms']['log4j']['rancid']              = {}
default['opennms']['log4j']['jmx']                 = {}
default['opennms']['log4j']['linkd']               = {}
default['opennms']['log4j']['web_map']             = {}
default['opennms']['log4j']['statsd']              = {}
default['opennms']['log4j']['instrumentation']     = {}
default['opennms']['log4j']['snmp4j_internal']     = {}
default['opennms']['log4j']['tl1d']                = {}
default['opennms']['log4j']['asterisk']            = {}
default['opennms']['log4j']['insproxy']            = {}
default['opennms']['log4j']['accesspointmonitor']  = {}
# magic-users.properties
default['opennms']['magic_users']['admin_users']     = "admin"
default['opennms']['magic_users']['ro_users']        = ""
default['opennms']['magic_users']['dashboard_users'] = ""
default['opennms']['magic_users']['provision_users'] = ""
default['opennms']['magic_users']['remoting_users']  = ""
default['opennms']['magic_users']['rest_users']      = "iphone"
# map.properties
default['opennms']['map']['severity']['critical']['label'] = "Critical"
default['opennms']['map']['severity']['critical']['color'] = "red"
default['opennms']['map']['severity']['critical']['flash'] = true
default['opennms']['map']['severity']['major']['label'] = "Major"
default['opennms']['map']['severity']['major']['color'] = "orange"
default['opennms']['map']['severity']['minor']['label'] = "Minor"
default['opennms']['map']['severity']['minor']['color'] = "yellow"
default['opennms']['map']['severity']['warning']['label'] = "Warning"
default['opennms']['map']['severity']['warning']['color'] = "cyan"
default['opennms']['map']['severity']['normal']['label'] = "Normal"
default['opennms']['map']['severity']['normal']['color'] = "green"
default['opennms']['map']['severity']['cleared']['label'] = "Cleared"
default['opennms']['map']['severity']['cleared']['color'] = "white"
default['opennms']['map']['severity']['indeterminate']['label'] = "Indeterminate"
default['opennms']['map']['severity']['indeterminate']['color'] = "lightblue"
default['opennms']['map']['severity']['default'] = "normal"
default['opennms']['map']['link']['ethernet']['text']      = "Ethernet"
default['opennms']['map']['link']['fastethernet']['text']  = "Fast Ethernet"
default['opennms']['map']['link']['fastethernet2']['text'] = "Fast Ethernet"
default['opennms']['map']['link']['gigaethernet']['text']  = "GigaBit Ethernet"
default['opennms']['map']['link']['gigaethernet2']['text'] = "GigaBit Ethernet"
default['opennms']['map']['link']['serial']['text']        = "Serial Line"
default['opennms']['map']['link']['framerelay']['text']    = "Frame Relay"
default['opennms']['map']['link']['ieee80211']['text']     = "WIFI"
default['opennms']['map']['link']['unknown']['text']       = "Unknown"
default['opennms']['map']['link']['dwo']['text']           = "DWO Connection"
default['opennms']['map']['link']['summary']['text']       = "SummaryLink"
default['opennms']['map']['link']['default']               = 9999
default['opennms']['map']['multilink']['max']              = 3
default['opennms']['map']['multilink']['status']           = "best"
default['opennms']['map']['multilink']['ignore_color']     = "yellow"
default['opennms']['map']['linkstatus']['up_color']        = "green"
default['opennms']['map']['linkstatus']['good_color']      = "green"
default['opennms']['map']['linkstatus']['down_color']      = "red"
default['opennms']['map']['linkstatus']['down_flash']      = "true"
default['opennms']['map']['linkstatus']['bad_color']       = "red"
default['opennms']['map']['linkstatus']['bad_flash']       = "true"
default['opennms']['map']['linkstatus']['admindown_color'] = "blue"
default['opennms']['map']['linkstatus']['testing_color']   = "orange"
default['opennms']['map']['linkstatus']['unknown_color']   = "grey"
default['opennms']['map']['status']['nodedown']['color']      = "red"
default['opennms']['map']['status']['nodedown']['text']       = "NodeDown"
default['opennms']['map']['status']['interfacedown']['color'] = "orange"
default['opennms']['map']['status']['interfacedown']['text']  = "InterfaceDown"
default['opennms']['map']['status']['linkdown']['color']      = "orange"
default['opennms']['map']['status']['linkdown']['text']       = "SNMPLinkDown"
default['opennms']['map']['status']['servicedown']['color']   = "yellow"
default['opennms']['map']['status']['servicedown']['text']    = "NodeLostService"
default['opennms']['map']['status']['undefined']['color']     = "grey"
default['opennms']['map']['status']['undefined']['text']      = "SeeEventDetails"
default['opennms']['map']['status']['nodeup']['color']        = "green"
default['opennms']['map']['status']['nodeup']['text']         = "NodeUp"
default['opennms']['map']['status']['default']                = "nodeup"
default['opennms']['map']['status']['unknown_uei']            = "undefined"
default['opennms']['map']['avail']['normal']['min']           = "99"
default['opennms']['map']['avail']['normal']['color']         = "green"
default['opennms']['map']['avail']['warning']['min']          = "97"
default['opennms']['map']['avail']['warning']['color']        = "yellow"
default['opennms']['map']['avail']['critical']['min']         = "0"
default['opennms']['map']['avail']['critical']['color']       = "red"
default['opennms']['map']['avail']['critical']['flash']       = true
default['opennms']['map']['avail']['undefined']['min']        = "-1"
default['opennms']['map']['avail']['undefined']['color']      = "grey"
default['opennms']['map']['avail']['enable']                  = true
default['opennms']['map']['icon']['desktop']          = "png/desktop.png"
default['opennms']['map']['icon']['infrastructure']   = "png/infrastructure.png"
default['opennms']['map']['icon']['laptop']           = "png/laptop.png"
default['opennms']['map']['icon']['opennms']          = "png/opennms.png"
default['opennms']['map']['icon']['other']            = "png/other.png"
default['opennms']['map']['icon']['printer']          = "png/printer.png"
default['opennms']['map']['icon']['server']           = "png/server.png"
default['opennms']['map']['icon']['telephony']        = "png/telephony.png"
default['opennms']['map']['icon']['unspecified']      = "png/unspecified.png"
default['opennms']['map']['icon']['map']              = "map.gif"
default['opennms']['map']['icon']['fileserver']       = "png/fileserver.png"
default['opennms']['map']['icon']['firewall']         = "png/firewall.png"
default['opennms']['map']['icon']['mainframe']        = "png/mainframe.png"
default['opennms']['map']['icon']['multilayerswitch'] = "png/multilayerswitch.png"
default['opennms']['map']['icon']['pix']              = "png/pix.png"
default['opennms']['map']['icon']['router']           = "png/router.png"
default['opennms']['map']['icon']['switch']           = "png/switch.png"
default['opennms']['map']['icon']['vax']              = "png/vax.png"
default['opennms']['map']['icon']['default_map']      = "map"
default['opennms']['map']['icon']['default_node']     = "unspecified"
default['opennms']['map']['cmenu']['node']['link']              = "element/node.jsp?node=ELEMENT_ID"
default['opennms']['map']['cmenu']['node']['params']            = "toolbar,width=1280,height=800, left=0, top=0, scrollbars=1, resizable=1"
default['opennms']['map']['cmenu']['telnet']['enabled']         = false
default['opennms']['map']['cmenu']['telnet']['link']            = "telnet://ELEMENT_HOSTNAME"
default['opennms']['map']['cmenu']['ping']['link']              = "map/response/ping.jsp?node=ELEMENT_ID"
default['opennms']['map']['cmenu']['ping']['params']            = "toolbar,width=300,height=300, left=0, top=0, scrollbars=1, resizable=1"
default['opennms']['map']['cmenu']['traceroute']['link']        = "map/response/traceroute.jsp?node=ELEMENT_ID"
default['opennms']['map']['cmenu']['traceroute']['params']      = "toolbar,width=300,height=300, left=0, top=0, scrollbars=1, resizable=1"
default['opennms']['map']['cmenu']['alarms']['link']            = "alarm/list.htm?sortby=id&acktype=unack&limit=20&filter=node%3DELEMENT_ID"
default['opennms']['map']['cmenu']['alarms']['params']          = "toolbar,width=1280,height=800, left=0, top=0, scrollbars=1, resizable=1"
default['opennms']['map']['cmenu']['events']['link']            = "event/list?filter=node%3DELEMENT_ID"
default['opennms']['map']['cmenu']['events']['params']          = "toolbar,width=1280,height=800, left=0, top=0, scrollbars=1, resizable=1"
default['opennms']['map']['cmenu']['resource_graphs']['link']   = "graph/chooseresource.htm?parentResourceType=node&parentResource=ELEMENT_ID&reports=all"
default['opennms']['map']['cmenu']['resource_graphs']['params'] = "toolbar,width=1280,height=800, left=0, top=0, scrollbars=1, resizable=1"
default['opennms']['map']['severity']['map'] = "worst"
default['opennms']['map']['enable']['reload']      = false
default['opennms']['map']['enable']['contextmenu'] = true
default['opennms']['map']['enable']['doubleclick'] = true
# microblog-configuration.xml 
# NOTE: To define a profile not named identica or twitter you'll need to define ...['service_url'] as well.
default['opennms']['microblog']['default_profile']['name']            = "identica"
default['opennms']['microblog']['default_profile']['authen_username'] = "yourusername"
default['opennms']['microblog']['default_profile']['authen_password'] = "yourpassword"

