# yum repo stuff
default['yum']['opennms']['key_url']                      = "http://yum.opennms.org/OPENNMS-GPG-KEY"
default['yum']['opennms-stable-common']['baseurl']        = "http://yum.opennms.org/stable/common"
default['yum']['opennms-stable-common']['failovermethod'] = "roundrobin"
default['yum']['opennms-stable-rhel6']['baseurl']         = "http://yum.opennms.org/stable/rhel6"
default['yum']['opennms-stable-rhel6']['failovermethod']  = "roundrobin"

# opennms.conf
default['opennms']['conf']['home']           = "/opt/opennms"
default['opennms']['conf']['pidfile']        = "#{default['opennms']['conf']['home']}/logs/daemon/opennms.pid"
default['opennms']['conf']['logdir']         = "#{default['opennms']['conf']['home']}/logs/daemon"
default['opennms']['conf']['initdir']        = "#{default['opennms']['conf']['home']}/bin"
default['opennms']['conf']['redirect']       = "$LOG_DIRECTORY/output.log"
default['opennms']['conf']['start_timeout']  = 10
default['opennms']['conf']['status_wait']    = 5
default['opennms']['conf']['heap_size']      = 512
default['opennms']['conf']['addl_mgr_opts']  = ""
default['opennms']['conf']['addl_classpath'] = ""
default['opennms']['conf']['use_incgc']      = ""
default['opennms']['conf']['hotspot']        = ""
default['opennms']['conf']['verbose_gc']     = ""
default['opennms']['conf']['runjava_opts']   = ""
default['opennms']['conf']['invoke_url']     = "http://127.0.0.1:8181/invoke?objectname=OpenNMS:Name=Manager"
default['opennms']['conf']['runas']          = "root"
default['opennms']['conf']['max_file_descr'] = "20480"
default['opennms']['conf']['command']        = "8192"

# opennms.properties
# ICMP
default['opennms']['properties']['icmp']['pinger_class'] = "org.opennms.netmgt.icmp.jni6.Jni6Pinger"
default['opennms']['properties']['icmp']['require_v4']   = nil
default['opennms']['properties']['icmp']['require_v6']   = nil
# SNMP
default['opennms']['properties']['snmp']['strategy_class']             = nil
default['opennms']['properties']['snmp']['smisyntaxes']                = "opennms-snmp4j-smisyntaxes.properties"
default['opennms']['properties']['snmp']['forward_runtime_exceptions'] = false
default['opennms']['properties']['snmp']['log_factory']                = "org.snmp4j.log.Log4jLogFactory"
default['opennms']['properties']['snmp']['allow_64bit_ipaddress']      = true
# Data collection
default['opennms']['properties']['dc']['store_by_group']          = false
default['opennms']['properties']['dc']['store_by_foreign_source'] = false
default['opennms']['properties']['dc']['rrd_base_dir']            = "#{default['opennms']['conf']['home']}/share/rrd"
default['opennms']['properties']['dc']['rrd_dc_dir']              = "/snmp/"
default['opennms']['properties']['dc']['rrd_binary']              = "/usr/bin/rrdtool"
default['opennms']['properties']['dc']['decimal_format']          = nil
default['opennms']['properties']['dc']['reload_check_interval']   = nil
default['opennms']['properties']['dc']['instrumentation_class']   = nil
default['opennms']['properties']['dc']['enable_check_file_mod']   = nil
default['opennms']['properties']['dc']['force_rescan']            = nil
default['opennms']['properties']['dc']['instance_limiting']       = nil
# Remote
default['opennms']['properties']['remote']['rmi_server_hostname']      = nil
default['opennms']['properties']['remote']['exclude_service_monitors'] = "DHCP,NSClient,RadiusAuth,XMP"
default['opennms']['properties']['remote']['min_config_reload_int']    = nil
# Ticketing
default['opennms']['properties']['ticket']['servicelayer']  = "org.opennms.netmgt.ticketd.DefaultTicketerServiceLayer"
default['opennms']['properties']['ticket']['plugin']        = "org.opennms.netmgt.ticketd.NullTicketerPlugin"
default['opennms']['properties']['ticket']['enabled']       = nil
default['opennms']['properties']['ticket']['link_template'] = nil
# Misc
default['opennms']['properties']['misc']['layout_applications_vertically'] = false
default['opennms']['properties']['misc']['bin_dir']                        = "#{default['opennms']['conf']['home']}/bin"
default['opennms']['properties']['misc']['webapp_logs_dir']                = "#{default['opennms']['conf']['home']}/logs/webapp"
default['opennms']['properties']['misc']['headless']                       = true
default['opennms']['properties']['misc']['find_by_service_type_query']     = nil
default['opennms']['properties']['misc']['load_snmp_data_on_init']         = nil
default['opennms']['properties']['misc']['allow_html_fields']              = nil
# Reporting
default['opennms']['properties']['reporting']['template_dir']         = "#{default['opennms']['conf']['home']}/etc"
default['opennms']['properties']['reporting']['report_dir']           = "#{default['opennms']['conf']['home']}/share/reports"
default['opennms']['properties']['reporting']['report_logo']          = "#{default['opennms']['conf']['home']}/webapps/images/logo.gif"
default['opennms']['properties']['reporting']['ksc_graphs_per_line']  = 1
default['opennms']['properties']['reporting']['jasper_version']       = "3.7.6"
# Eventd IPC
default['opennms']['properties']['eventd']['proxy_host']     = nil
default['opennms']['properties']['eventd']['proxy_port']     = nil
default['opennms']['properties']['eventd']['proxy_timeout']  = nil
# RANCID
default['opennms']['properties']['rancid']['enabled']              = nil
default['opennms']['properties']['rancid']['only_rancid_adapter']  = nil
# RTC IPC
default['opennms']['properties']['rtc']['baseurl']   = "http://localhost:8980/opennms/rtc/post"
default['opennms']['properties']['rtc']['username']  = "rtc"
default['opennms']['properties']['rtc']['password']  = "rtc"
# MAP IPC
default['opennms']['properties']['map']['baseurl']   = "http://localhost:8980/opennms/map/post"
default['opennms']['properties']['map']['username']  = "map"
default['opennms']['properties']['map']['password']  = "map"
# JETTY
default['opennms']['properties']['jetty']['port']                   = 8980
default['opennms']['properties']['jetty']['ajp']                    = nil
default['opennms']['properties']['jetty']['host']                   = nil
default['opennms']['properties']['jetty']['max_form_content_size']  = nil
default['opennms']['properties']['jetty']['request_header_size']    = nil
default['opennms']['properties']['jetty']['max_form_keys']          = 2000
default['opennms']['properties']['jetty']['https_port']             = nil
default['opennms']['properties']['jetty']['https_host']             = nil
default['opennms']['properties']['jetty']['keystore']               = nil
default['opennms']['properties']['jetty']['ks_password']            = nil
default['opennms']['properties']['jetty']['key_password']           = nil
default['opennms']['properties']['jetty']['cert_alias']             = nil
default['opennms']['properties']['jetty']['exclude_cipher_suites']  = nil
default['opennms']['properties']['jetty']['https_baseurl']          = nil
# UI
default['opennms']['properties']['ui']['acls']                        = nil
default['opennms']['properties']['ui']['ack']                         = false
default['opennms']['properties']['ui']['show_count']                  = false
default['opennms']['properties']['ui']['show_outage_nodes']           = nil
default['opennms']['properties']['ui']['show_problem_nodes']          = nil
default['opennms']['properties']['ui']['outage_node_count']           = nil
default['opennms']['properties']['ui']['problem_node_count']          = nil
default['opennms']['properties']['ui']['show_node_status_bar']        = nil
default['opennms']['properties']['ui']['disable_login_success_event'] = nil
default['opennms']['properties']['ui']['center_url']                  = nil
# Asterisk AGI
default['opennms']['properties']['asterisk']['listen_address'] = nil
default['opennms']['properties']['asterisk']['listen_port']    = nil
default['opennms']['properties']['asterisk']['max_pool_size']  = nil
# Provisioning
default['opennms']['properties']['provisioning']['dns_server']                = "127.0.0.1"
default['opennms']['properties']['provisioning']['max_concurrent_xtn']        = nil
default['opennms']['properties']['provisioning']['enable_discovery']          = nil
default['opennms']['properties']['provisioning']['enable_deletions']          = nil
default['opennms']['properties']['provisioning']['schedule_existing_rescans'] = nil
default['opennms']['properties']['provisioning']['schedule_updated_rescans']  = nil
# SMS Gateway
default['opennms']['properties']['sms']['serial_ports']  = "/dev/ttyACM0:/dev/ttyACM1:/dev/ttyACM2:/dev/ttyACM3:/dev/ttyACM4:/dev/ttyACM5"
default['opennms']['properties']['sms']['polling']       = true
# Mapping / Geocoding
default['opennms']['properties']['geo']['map_type']       = "OpenLayers"
default['opennms']['properties']['geo']['api_key']        = ""
default['opennms']['properties']['geo']['geocoder_class'] = "org.opennms.features.poller.remote.gwt.server.geocoding.NullGeocoder"
default['opennms']['properties']['geo']['rate']           = 10
default['opennms']['properties']['geo']['referrer']       = "http://localhost/"
default['opennms']['properties']['geo']['min_quality']    = "ZIP"
default['opennms']['properties']['geo']['email']          = ""
default['opennms']['properties']['geo']['tile_url']       = "http://otile1.mqcdn.com/tiles/1.0.0/osm/${z}/${x}/${y}.png"
# capsd-configuration.xml
default['opennms']['capsd']['rescan_frequency']     = 86400000
default['opennms']['capsd']['initial_sleep_time']   =  30000
default['opennms']['capsd']['max_suspect_threads']  = 6
default['opennms']['capsd']['max_rescan_threads']   = 3
default['opennms']['capsd']['icmp']['enabled']      = true
default['opennms']['capsd']['icmp']['scan']         = "on"
default['opennms']['capsd']['icmp']['timeout']      = 2000
default['opennms']['capsd']['icmp']['retry']        = 1
default['opennms']['capsd']['strafeping']['enabled'] = true
default['opennms']['capsd']['strafeping']['scan']    = "on"
default['opennms']['capsd']['strafeping']['timeout'] = 2000
default['opennms']['capsd']['strafeping']['retry']   = 1
default['opennms']['capsd']['snmp']['enabled'] = true
default['opennms']['capsd']['snmp']['scan']    = "on"
default['opennms']['capsd']['snmp']['timeout'] = 2000
default['opennms']['capsd']['snmp']['retry']   = 1
default['opennms']['capsd']['http']['enabled'] = true
default['opennms']['capsd']['http']['port']    = 80
default['opennms']['capsd']['http']['scan']    = "on"
default['opennms']['capsd']['http']['timeout'] = 3000
default['opennms']['capsd']['http']['retry']   = 1
default['opennms']['capsd']['http_8080']['enabled'] = true
default['opennms']['capsd']['http_8080']['port']    = 8080
default['opennms']['capsd']['http_8080']['scan']    = "on"
default['opennms']['capsd']['http_8080']['timeout'] = 3000
default['opennms']['capsd']['http_8080']['retry']   = 1
default['opennms']['capsd']['http_8000']['enabled'] = true
default['opennms']['capsd']['http_8000']['port']    = 8000
default['opennms']['capsd']['http_8000']['scan']    = "on"
default['opennms']['capsd']['http_8000']['timeout'] = 3000
default['opennms']['capsd']['http_8000']['retry']   = 1
default['opennms']['capsd']['https']['enabled'] = true
default['opennms']['capsd']['https']['port']    = 443
default['opennms']['capsd']['https']['scan']    = "on"
default['opennms']['capsd']['https']['timeout'] = 5000
default['opennms']['capsd']['https']['retry']   = 1
default['opennms']['capsd']['hyperic_agent']['enabled'] = true
default['opennms']['capsd']['hyperic_agent']['port']    = 2144
default['opennms']['capsd']['hyperic_agent']['scan']    = "on"
default['opennms']['capsd']['hyperic_agent']['timeout'] = 2000
default['opennms']['capsd']['hyperic_agent']['retry']   = 1
default['opennms']['capsd']['hyperichq']['enabled'] = true
default['opennms']['capsd']['hyperichq']['port']    = 7080
default['opennms']['capsd']['hyperichq']['scan']    = "off"
default['opennms']['capsd']['hyperichq']['timeout'] = 2000
default['opennms']['capsd']['hyperichq']['retry']   = 1
default['opennms']['capsd']['ftp']['enabled'] = true
default['opennms']['capsd']['ftp']['port']    = 21
default['opennms']['capsd']['ftp']['scan']    = "on"
default['opennms']['capsd']['ftp']['timeout'] = 2000
default['opennms']['capsd']['ftp']['retry']   = 1
default['opennms']['capsd']['telnet']['enabled'] = true
default['opennms']['capsd']['telnet']['banner']  = "*"
default['opennms']['capsd']['telnet']['port']    = 23
default['opennms']['capsd']['telnet']['scan']    = "on"
default['opennms']['capsd']['telnet']['timeout'] = 3000
default['opennms']['capsd']['telnet']['retry']   = 1
default['opennms']['capsd']['dns']['enabled'] = true
default['opennms']['capsd']['dns']['lookup']  = "localhost"
default['opennms']['capsd']['dns']['port']    = 53
default['opennms']['capsd']['dns']['scan']    = "on"
default['opennms']['capsd']['dns']['timeout'] = 5000
default['opennms']['capsd']['dns']['retry']   = 1
default['opennms']['capsd']['imap']['enabled'] = true
default['opennms']['capsd']['imap']['port']    = 143
default['opennms']['capsd']['imap']['scan']    = "on"
default['opennms']['capsd']['imap']['timeout'] = 3000
default['opennms']['capsd']['imap']['retry']   = 1
default['opennms']['capsd']['msexchange']['enabled']   = true
default['opennms']['capsd']['msexchange']['pop3_port'] = 110
default['opennms']['capsd']['msexchange']['imap_port'] = 143
default['opennms']['capsd']['msexchange']['mapi_port'] = 593
default['opennms']['capsd']['msexchange']['scan']      = "on"
default['opennms']['capsd']['msexchange']['timeout']   = 3000
default['opennms']['capsd']['msexchange']['retry']     = 1
default['opennms']['capsd']['smtp']['enabled'] = true
default['opennms']['capsd']['smtp']['port']    = 25
default['opennms']['capsd']['smtp']['scan']    = "on"
default['opennms']['capsd']['smtp']['timeout'] = 3000
default['opennms']['capsd']['smtp']['retry']   = 1
default['opennms']['capsd']['pop3']['enabled'] = true
default['opennms']['capsd']['pop3']['port']    = 110
default['opennms']['capsd']['pop3']['scan']    = "on"
default['opennms']['capsd']['pop3']['timeout'] = 3000
default['opennms']['capsd']['pop3']['retry']   = 1
default['opennms']['capsd']['ssh']['enabled'] = true
default['opennms']['capsd']['ssh']['port']    = 22
default['opennms']['capsd']['ssh']['banner']  = "SSH"
default['opennms']['capsd']['ssh']['scan']    = "on"
default['opennms']['capsd']['ssh']['timeout'] = 3000
default['opennms']['capsd']['ssh']['retry'] = 1
default['opennms']['capsd']['mysql']['enabled'] = true
default['opennms']['capsd']['mysql']['port']    = 3306
default['opennms']['capsd']['mysql']['banner']  = "*"
default['opennms']['capsd']['mysql']['scan']    = "on"
default['opennms']['capsd']['mysql']['timeout'] = 3000
default['opennms']['capsd']['mysql']['retry']   = 1
default['opennms']['capsd']['sqlserver']['enabled'] = true
default['opennms']['capsd']['sqlserver']['port']    = 1433
default['opennms']['capsd']['sqlserver']['banner']  = "*"
default['opennms']['capsd']['sqlserver']['scan']    = "on"
default['opennms']['capsd']['sqlserver']['timeout'] = 3000
default['opennms']['capsd']['sqlserver']['retry']   = 1
default['opennms']['capsd']['oracle']['enabled'] = true
default['opennms']['capsd']['oracle']['port']    = 1521
default['opennms']['capsd']['oracle']['banner']  = "*"
default['opennms']['capsd']['oracle']['scan']    = "on"
default['opennms']['capsd']['oracle']['timeout'] = 3000
default['opennms']['capsd']['oracle']['retry']   = 1
default['opennms']['capsd']['postgres']['enabled'] = true
default['opennms']['capsd']['postgres']['port']    = 5432
default['opennms']['capsd']['postgres']['banner']  = "*"
default['opennms']['capsd']['postgres']['scan']    = "on"
default['opennms']['capsd']['postgres']['timeout'] = 3000
default['opennms']['capsd']['postgres']['retry']   = 1
default['opennms']['capsd']['router']['enabled'] = true
default['opennms']['capsd']['router']['vbname']  = ".1.3.6.1.2.1.4.1.0"
default['opennms']['capsd']['router']['vbvalue'] = 1
default['opennms']['capsd']['router']['scan']    = "on"
default['opennms']['capsd']['router']['timeout'] = 2000
default['opennms']['capsd']['router']['retry']   = 1
default['opennms']['capsd']['hp_insight_manager']['enabled'] = true
default['opennms']['capsd']['hp_insight_manager']['banner']  = "*"
default['opennms']['capsd']['hp_insight_manager']['port']    = 2381
default['opennms']['capsd']['hp_insight_manager']['scan']    = "on"
default['opennms']['capsd']['hp_insight_manager']['timeout'] = 3000
default['opennms']['capsd']['hp_insight_manager']['retry']   = 1
default['opennms']['capsd']['dell_openmanage']['enabled'] = true
default['opennms']['capsd']['dell_openmanage']['banner']  = "*"
default['opennms']['capsd']['dell_openmanage']['port']    = 1311
default['opennms']['capsd']['dell_openmanage']['scan']    = "on"
default['opennms']['capsd']['dell_openmanage']['timeout'] = 3000
default['opennms']['capsd']['dell_openmanage']['retry']   = 1
default['opennms']['capsd']['nrpe']['enabled'] = true
default['opennms']['capsd']['nrpe']['banner']  = "*"
default['opennms']['capsd']['nrpe']['command'] = "_NRPE_CHECK"
default['opennms']['capsd']['nrpe']['port']    = 5666
default['opennms']['capsd']['nrpe']['scan']    = "on"
default['opennms']['capsd']['nrpe']['timeout'] = 3000
default['opennms']['capsd']['nrpe']['retry']   = 2
default['opennms']['capsd']['nrpe_nossl']['enabled'] = true
default['opennms']['capsd']['nrpe_nossl']['banner']  = "*"
default['opennms']['capsd']['nrpe_nossl']['command'] = "_NRPE_CHECK"
default['opennms']['capsd']['nrpe_nossl']['usessl']  = false
default['opennms']['capsd']['nrpe_nossl']['port']    = 5666
default['opennms']['capsd']['nrpe_nossl']['scan']    = "on"
default['opennms']['capsd']['nrpe_nossl']['timeout'] = 3000
default['opennms']['capsd']['nrpe_nossl']['retry']   = 2
default['opennms']['capsd']['windows_task_scheduler']['enabled'] = true
default['opennms']['capsd']['windows_task_scheduler']['service_name']  = "Task Scheduler"
default['opennms']['capsd']['windows_task_scheduler']['scan']    = "on"
default['opennms']['capsd']['windows_task_scheduler']['timeout'] = 2000
default['opennms']['capsd']['windows_task_scheduler']['retry']   = 1
default['opennms']['capsd']['opennms_jvm']['enabled']  = true
default['opennms']['capsd']['opennms_jvm']['port']     = 18980
default['opennms']['capsd']['opennms_jvm']['factory']  = "PASSWORD-CLEAR"
default['opennms']['capsd']['opennms_jvm']['username'] = "admin"
default['opennms']['capsd']['opennms_jvm']['password'] = "admin"
default['opennms']['capsd']['opennms_jvm']['protocol'] = "rmi"
default['opennms']['capsd']['opennms_jvm']['url_path'] = "/jmxrmi"
default['opennms']['capsd']['opennms_jvm']['scan']     = "on"
default['opennms']['capsd']['opennms_jvm']['timeout']  = 3000
default['opennms']['capsd']['opennms_jvm']['retry']    = 2
default['opennms']['capsd']['opennms_jvm']['type']     = "default"
default['opennms']['categories']['common_rule']        = "IPADDR != '0.0.0.0'"
default['opennms']['categories']['overall']['enable']   = true
default['opennms']['categories']['overall']['label']    = "Overall Service Availability"
default['opennms']['categories']['overall']['comment']  = "This category reflects availability of all services currently being monitored by OpenNMS."
default['opennms']['categories']['overall']['normal']   = 99.99
default['opennms']['categories']['overall']['warning']  = 97
default['opennms']['categories']['overall']['services'] = []
default['opennms']['categories']['overall']['rule']     = "IPADDR != '0.0.0.0'"
default['opennms']['categories']['interfaces']['enable']   = true
default['opennms']['categories']['interfaces']['label']    = "Network Interfaces"
default['opennms']['categories']['interfaces']['comment']  = "This category reflects the ability to 'ping' managed devices and SNMP agents.  'Ping', using the ICMP protocol, tests a devices network connectivity/availability."
default['opennms']['categories']['interfaces']['normal']   = 99.99
default['opennms']['categories']['interfaces']['warning']  = 97
default['opennms']['categories']['interfaces']['services'] = ["ICMP,SNMP"]
default['opennms']['categories']['interfaces']['rule']     = "isICMP | isSNMP) & (IPADDR != '0.0.0.0')"
default['opennms']['categories']['email']['enable']   = true
default['opennms']['categories']['email']['label']    = "Email Servers"
default['opennms']['categories']['email']['comment']  = "This category includes all managed interfaces which are running an Email service, including SMTP, POP3, or IMAP.  This will include MS Exchange servers running these protocols."
default['opennms']['categories']['email']['normal']   = 99.99
default['opennms']['categories']['email']['warning']  = 97
default['opennms']['categories']['email']['services'] = ["SMTP","POP3","IMAP"]
default['opennms']['categories']['email']['rule']     = "isSMTP | isPOP3 | isIMAP"
default['opennms']['categories']['web']['enable']   = true
default['opennms']['categories']['web']['label']    = "Web Servers"
default['opennms']['categories']['web']['comment']  = "This category includes all managed interfaces which are running an HTTP (Web) server on port 80 or other common ports."
default['opennms']['categories']['web']['normal']   = 99.99
default['opennms']['categories']['web']['warning']  = 97
default['opennms']['categories']['web']['services'] = ["HTTP","HTTPS","HTTP-8000","HTTP-8080"]
default['opennms']['categories']['web']['rule']     = "isHTTP | isHTTPS | isHTTP-8000 | isHTTP-8080"
default['opennms']['categories']['jmx']['enable']   = true
default['opennms']['categories']['jmx']['label']    = "JMX Servers"
default['opennms']['categories']['jmx']['comment']  = "This category includes all managed interfaces which are running JMX servers."
default['opennms']['categories']['jmx']['normal']   = 99.99
default['opennms']['categories']['jmx']['warning']  = 97
default['opennms']['categories']['jmx']['services'] = ["JBoss4","JBoss32","JVM"]
default['opennms']['categories']['jmx']['rule']     = "isJBoss4 | isJBoss32 | isJVM"
default['opennms']['categories']['dns']['enable']   = true
default['opennms']['categories']['dns']['label']    = "DNS and DHCP Servers"
default['opennms']['categories']['dns']['comment']  = "This category includes all managed interfaces which are running either DNS (name resolution) servers or DHCP servers."
default['opennms']['categories']['dns']['normal']   = 99.99
default['opennms']['categories']['dns']['warning']  = 97
default['opennms']['categories']['dns']['services'] = ["DNS","DHCP"]
default['opennms']['categories']['dns']['rule']     = "isDNS | isDHCP"
default['opennms']['categories']['db']['enable']   = true
default['opennms']['categories']['db']['label']    = "Database Servers"
default['opennms']['categories']['db']['comment']  = "This category includes all managed interfaces which are currently running PostgreSQL, MySQL, SQLServer, or Oracle database servers."
default['opennms']['categories']['db']['normal']   = 99.99
default['opennms']['categories']['db']['warning']  = 97
default['opennms']['categories']['db']['services'] = ["MySQL","Oracle","Postgres","SQLServer"]
default['opennms']['categories']['db']['rule']     = "isMySQL | isOracle | isPostgres | isSQLServer"
default['opennms']['categories']['other']['enable']   = true
default['opennms']['categories']['other']['label']    = "Other Servers"
default['opennms']['categories']['other']['comment']  = "This category includes all managed interfaces which are running FTP (file transfer protocol) servers or SSH (secure shell) servers."
default['opennms']['categories']['other']['normal']   = 99.99
default['opennms']['categories']['other']['warning']  = 97
default['opennms']['categories']['other']['services'] = ["FTP","SSH"]
default['opennms']['categories']['other']['rule']     = "isFTP | isSSH"
default['opennms']['categories']['inet']['enable']   = true
default['opennms']['categories']['inet']['label']    = "Internet Connectivity"
default['opennms']['categories']['inet']['comment']  = "This category reflects the ability to 'ping' the router at the ISP-end of your Internet connection."
default['opennms']['categories']['inet']['normal']   = 99.99
default['opennms']['categories']['inet']['warning']  = 97
default['opennms']['categories']['inet']['services'] = ["ICMP"]
default['opennms']['categories']['inet']['rule']     = "ipaddr == '0.0.0.0'"

